// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: scheduler_controller.proto

package bit.workflowScheduler.grpc.scheduler_controller.gencode;

/**
 * Protobuf type {@code bit.workflowScheduler.grpc.scheduler_controller.gencode.InputWorkflowRequest}
 */
public  final class InputWorkflowRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:bit.workflowScheduler.grpc.scheduler_controller.gencode.InputWorkflowRequest)
    InputWorkflowRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use InputWorkflowRequest.newBuilder() to construct.
  private InputWorkflowRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private InputWorkflowRequest() {
    workflow_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private InputWorkflowRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
              workflow_ = new java.util.ArrayList<com.google.protobuf.ByteString>();
              mutable_bitField0_ |= 0x00000001;
            }
            workflow_.add(input.readBytes());
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
        workflow_ = java.util.Collections.unmodifiableList(workflow_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return bit.workflowScheduler.grpc.scheduler_controller.gencode.SchedulerControllerOuterClass.internal_static_bit_workflowScheduler_grpc_scheduler_controller_gencode_InputWorkflowRequest_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return bit.workflowScheduler.grpc.scheduler_controller.gencode.SchedulerControllerOuterClass.internal_static_bit_workflowScheduler_grpc_scheduler_controller_gencode_InputWorkflowRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            bit.workflowScheduler.grpc.scheduler_controller.gencode.InputWorkflowRequest.class, bit.workflowScheduler.grpc.scheduler_controller.gencode.InputWorkflowRequest.Builder.class);
  }

  public static final int WORKFLOW_FIELD_NUMBER = 1;
  private java.util.List<com.google.protobuf.ByteString> workflow_;
  /**
   * <pre>
   * </pre>
   *
   * <code>repeated bytes workflow = 1;</code>
   */
  public java.util.List<com.google.protobuf.ByteString>
      getWorkflowList() {
    return workflow_;
  }
  /**
   * <pre>
   * </pre>
   *
   * <code>repeated bytes workflow = 1;</code>
   */
  public int getWorkflowCount() {
    return workflow_.size();
  }
  /**
   * <pre>
   * </pre>
   *
   * <code>repeated bytes workflow = 1;</code>
   */
  public com.google.protobuf.ByteString getWorkflow(int index) {
    return workflow_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < workflow_.size(); i++) {
      output.writeBytes(1, workflow_.get(i));
    }
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    {
      int dataSize = 0;
      for (int i = 0; i < workflow_.size(); i++) {
        dataSize += com.google.protobuf.CodedOutputStream
          .computeBytesSizeNoTag(workflow_.get(i));
      }
      size += dataSize;
      size += 1 * getWorkflowList().size();
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof bit.workflowScheduler.grpc.scheduler_controller.gencode.InputWorkflowRequest)) {
      return super.equals(obj);
    }
    bit.workflowScheduler.grpc.scheduler_controller.gencode.InputWorkflowRequest other = (bit.workflowScheduler.grpc.scheduler_controller.gencode.InputWorkflowRequest) obj;

    boolean result = true;
    result = result && getWorkflowList()
        .equals(other.getWorkflowList());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getWorkflowCount() > 0) {
      hash = (37 * hash) + WORKFLOW_FIELD_NUMBER;
      hash = (53 * hash) + getWorkflowList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static bit.workflowScheduler.grpc.scheduler_controller.gencode.InputWorkflowRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static bit.workflowScheduler.grpc.scheduler_controller.gencode.InputWorkflowRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static bit.workflowScheduler.grpc.scheduler_controller.gencode.InputWorkflowRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static bit.workflowScheduler.grpc.scheduler_controller.gencode.InputWorkflowRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static bit.workflowScheduler.grpc.scheduler_controller.gencode.InputWorkflowRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static bit.workflowScheduler.grpc.scheduler_controller.gencode.InputWorkflowRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static bit.workflowScheduler.grpc.scheduler_controller.gencode.InputWorkflowRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static bit.workflowScheduler.grpc.scheduler_controller.gencode.InputWorkflowRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static bit.workflowScheduler.grpc.scheduler_controller.gencode.InputWorkflowRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static bit.workflowScheduler.grpc.scheduler_controller.gencode.InputWorkflowRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static bit.workflowScheduler.grpc.scheduler_controller.gencode.InputWorkflowRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static bit.workflowScheduler.grpc.scheduler_controller.gencode.InputWorkflowRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(bit.workflowScheduler.grpc.scheduler_controller.gencode.InputWorkflowRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code bit.workflowScheduler.grpc.scheduler_controller.gencode.InputWorkflowRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:bit.workflowScheduler.grpc.scheduler_controller.gencode.InputWorkflowRequest)
      bit.workflowScheduler.grpc.scheduler_controller.gencode.InputWorkflowRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return bit.workflowScheduler.grpc.scheduler_controller.gencode.SchedulerControllerOuterClass.internal_static_bit_workflowScheduler_grpc_scheduler_controller_gencode_InputWorkflowRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return bit.workflowScheduler.grpc.scheduler_controller.gencode.SchedulerControllerOuterClass.internal_static_bit_workflowScheduler_grpc_scheduler_controller_gencode_InputWorkflowRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              bit.workflowScheduler.grpc.scheduler_controller.gencode.InputWorkflowRequest.class, bit.workflowScheduler.grpc.scheduler_controller.gencode.InputWorkflowRequest.Builder.class);
    }

    // Construct using bit.workflowScheduler.grpc.scheduler_controller.gencode.InputWorkflowRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      workflow_ = java.util.Collections.emptyList();
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return bit.workflowScheduler.grpc.scheduler_controller.gencode.SchedulerControllerOuterClass.internal_static_bit_workflowScheduler_grpc_scheduler_controller_gencode_InputWorkflowRequest_descriptor;
    }

    public bit.workflowScheduler.grpc.scheduler_controller.gencode.InputWorkflowRequest getDefaultInstanceForType() {
      return bit.workflowScheduler.grpc.scheduler_controller.gencode.InputWorkflowRequest.getDefaultInstance();
    }

    public bit.workflowScheduler.grpc.scheduler_controller.gencode.InputWorkflowRequest build() {
      bit.workflowScheduler.grpc.scheduler_controller.gencode.InputWorkflowRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public bit.workflowScheduler.grpc.scheduler_controller.gencode.InputWorkflowRequest buildPartial() {
      bit.workflowScheduler.grpc.scheduler_controller.gencode.InputWorkflowRequest result = new bit.workflowScheduler.grpc.scheduler_controller.gencode.InputWorkflowRequest(this);
      int from_bitField0_ = bitField0_;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        workflow_ = java.util.Collections.unmodifiableList(workflow_);
        bitField0_ = (bitField0_ & ~0x00000001);
      }
      result.workflow_ = workflow_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof bit.workflowScheduler.grpc.scheduler_controller.gencode.InputWorkflowRequest) {
        return mergeFrom((bit.workflowScheduler.grpc.scheduler_controller.gencode.InputWorkflowRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(bit.workflowScheduler.grpc.scheduler_controller.gencode.InputWorkflowRequest other) {
      if (other == bit.workflowScheduler.grpc.scheduler_controller.gencode.InputWorkflowRequest.getDefaultInstance()) return this;
      if (!other.workflow_.isEmpty()) {
        if (workflow_.isEmpty()) {
          workflow_ = other.workflow_;
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          ensureWorkflowIsMutable();
          workflow_.addAll(other.workflow_);
        }
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      bit.workflowScheduler.grpc.scheduler_controller.gencode.InputWorkflowRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (bit.workflowScheduler.grpc.scheduler_controller.gencode.InputWorkflowRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.util.List<com.google.protobuf.ByteString> workflow_ = java.util.Collections.emptyList();
    private void ensureWorkflowIsMutable() {
      if (!((bitField0_ & 0x00000001) == 0x00000001)) {
        workflow_ = new java.util.ArrayList<com.google.protobuf.ByteString>(workflow_);
        bitField0_ |= 0x00000001;
       }
    }
    /**
     * <pre>
     * </pre>
     *
     * <code>repeated bytes workflow = 1;</code>
     */
    public java.util.List<com.google.protobuf.ByteString>
        getWorkflowList() {
      return java.util.Collections.unmodifiableList(workflow_);
    }
    /**
     * <pre>
     * </pre>
     *
     * <code>repeated bytes workflow = 1;</code>
     */
    public int getWorkflowCount() {
      return workflow_.size();
    }
    /**
     * <pre>
     * </pre>
     *
     * <code>repeated bytes workflow = 1;</code>
     */
    public com.google.protobuf.ByteString getWorkflow(int index) {
      return workflow_.get(index);
    }
    /**
     * <pre>
     * </pre>
     *
     * <code>repeated bytes workflow = 1;</code>
     */
    public Builder setWorkflow(
        int index, com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureWorkflowIsMutable();
      workflow_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * </pre>
     *
     * <code>repeated bytes workflow = 1;</code>
     */
    public Builder addWorkflow(com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureWorkflowIsMutable();
      workflow_.add(value);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * </pre>
     *
     * <code>repeated bytes workflow = 1;</code>
     */
    public Builder addAllWorkflow(
        java.lang.Iterable<? extends com.google.protobuf.ByteString> values) {
      ensureWorkflowIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, workflow_);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * </pre>
     *
     * <code>repeated bytes workflow = 1;</code>
     */
    public Builder clearWorkflow() {
      workflow_ = java.util.Collections.emptyList();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:bit.workflowScheduler.grpc.scheduler_controller.gencode.InputWorkflowRequest)
  }

  // @@protoc_insertion_point(class_scope:bit.workflowScheduler.grpc.scheduler_controller.gencode.InputWorkflowRequest)
  private static final bit.workflowScheduler.grpc.scheduler_controller.gencode.InputWorkflowRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new bit.workflowScheduler.grpc.scheduler_controller.gencode.InputWorkflowRequest();
  }

  public static bit.workflowScheduler.grpc.scheduler_controller.gencode.InputWorkflowRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<InputWorkflowRequest>
      PARSER = new com.google.protobuf.AbstractParser<InputWorkflowRequest>() {
    public InputWorkflowRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new InputWorkflowRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<InputWorkflowRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<InputWorkflowRequest> getParserForType() {
    return PARSER;
  }

  public bit.workflowScheduler.grpc.scheduler_controller.gencode.InputWorkflowRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

