// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: scheduler_controller.proto

package bit.workflowScheduler.grpc.scheduler_controller.gencode;

public interface InputWorkflowRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:bit.workflowScheduler.grpc.scheduler_controller.gencode.InputWorkflowRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * </pre>
   *
   * <code>repeated bytes workflow = 1;</code>
   */
  java.util.List<com.google.protobuf.ByteString> getWorkflowList();
  /**
   * <pre>
   * </pre>
   *
   * <code>repeated bytes workflow = 1;</code>
   */
  int getWorkflowCount();
  /**
   * <pre>
   * </pre>
   *
   * <code>repeated bytes workflow = 1;</code>
   */
  com.google.protobuf.ByteString getWorkflow(int index);
}
