// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: scheduler_controller.proto

package bit.workflowScheduler.grpc.scheduler_controller.gencode;

public interface KeepAliveReplyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:bit.workflowScheduler.grpc.scheduler_controller.gencode.KeepAliveReply)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 下一次发送保活信号等待时间(从收到此应答到再次发送保活信号的等待时间，单位：秒)
   * 不会小于 1 秒
   * </pre>
   *
   * <code>int32 wait_secs = 1;</code>
   */
  int getWaitSecs();
}
