// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: scheduler_controller.proto

package bit.workflowScheduler.grpc.scheduler_controller.gencode;

public interface KeepAliveRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:bit.workflowScheduler.grpc.scheduler_controller.gencode.KeepAliveRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 调度器id
   * </pre>
   *
   * <code>string sid = 1;</code>
   */
  java.lang.String getSid();
  /**
   * <pre>
   * 调度器id
   * </pre>
   *
   * <code>string sid = 1;</code>
   */
  com.google.protobuf.ByteString
      getSidBytes();

  /**
   * <pre>
   * 调度器自测压力值（0~100，整数）
   * </pre>
   *
   * <code>fixed32 pressure = 2;</code>
   */
  int getPressure();

  /**
   * <pre>
   * 调度器承载力（还可以承载/接收多少工作流，单位：个，整数）
   * </pre>
   *
   * <code>fixed32 capacity = 3;</code>
   */
  int getCapacity();

  /**
   * <pre>
   * 保活序号（单调增，整数，从1开始）
   * </pre>
   *
   * <code>uint64 serial_number = 4;</code>
   */
  long getSerialNumber();

  /**
   * <pre>
   * ipv4地址(ip:port)
   * </pre>
   *
   * <code>string ipv4 = 5;</code>
   */
  java.lang.String getIpv4();
  /**
   * <pre>
   * ipv4地址(ip:port)
   * </pre>
   *
   * <code>string ipv4 = 5;</code>
   */
  com.google.protobuf.ByteString
      getIpv4Bytes();

  /**
   * <pre>
   * 集群id（必须保证与集群内资源分配器使用相同的集群id）
   * </pre>
   *
   * <code>string cluster_id = 6;</code>
   */
  java.lang.String getClusterId();
  /**
   * <pre>
   * 集群id（必须保证与集群内资源分配器使用相同的集群id）
   * </pre>
   *
   * <code>string cluster_id = 6;</code>
   */
  com.google.protobuf.ByteString
      getClusterIdBytes();
}
