// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: scheduler_controller.proto

package bit.workflowScheduler.grpc.scheduler_controller.gencode;

/**
 * Protobuf type {@code bit.workflowScheduler.grpc.scheduler_controller.gencode.KeepAliveReply}
 */
public  final class KeepAliveReply extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:bit.workflowScheduler.grpc.scheduler_controller.gencode.KeepAliveReply)
    KeepAliveReplyOrBuilder {
private static final long serialVersionUID = 0L;
  // Use KeepAliveReply.newBuilder() to construct.
  private KeepAliveReply(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private KeepAliveReply() {
    waitSecs_ = 0;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private KeepAliveReply(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 8: {

            waitSecs_ = input.readInt32();
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return bit.workflowScheduler.grpc.scheduler_controller.gencode.SchedulerControllerOuterClass.internal_static_bit_workflowScheduler_grpc_scheduler_controller_gencode_KeepAliveReply_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return bit.workflowScheduler.grpc.scheduler_controller.gencode.SchedulerControllerOuterClass.internal_static_bit_workflowScheduler_grpc_scheduler_controller_gencode_KeepAliveReply_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            bit.workflowScheduler.grpc.scheduler_controller.gencode.KeepAliveReply.class, bit.workflowScheduler.grpc.scheduler_controller.gencode.KeepAliveReply.Builder.class);
  }

  public static final int WAIT_SECS_FIELD_NUMBER = 1;
  private int waitSecs_;
  /**
   * <pre>
   * 下一次发送保活信号等待时间(从收到此应答到再次发送保活信号的等待时间，单位：秒)
   * 不会小于 1 秒
   * </pre>
   *
   * <code>int32 wait_secs = 1;</code>
   */
  public int getWaitSecs() {
    return waitSecs_;
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (waitSecs_ != 0) {
      output.writeInt32(1, waitSecs_);
    }
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (waitSecs_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, waitSecs_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof bit.workflowScheduler.grpc.scheduler_controller.gencode.KeepAliveReply)) {
      return super.equals(obj);
    }
    bit.workflowScheduler.grpc.scheduler_controller.gencode.KeepAliveReply other = (bit.workflowScheduler.grpc.scheduler_controller.gencode.KeepAliveReply) obj;

    boolean result = true;
    result = result && (getWaitSecs()
        == other.getWaitSecs());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + WAIT_SECS_FIELD_NUMBER;
    hash = (53 * hash) + getWaitSecs();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static bit.workflowScheduler.grpc.scheduler_controller.gencode.KeepAliveReply parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static bit.workflowScheduler.grpc.scheduler_controller.gencode.KeepAliveReply parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static bit.workflowScheduler.grpc.scheduler_controller.gencode.KeepAliveReply parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static bit.workflowScheduler.grpc.scheduler_controller.gencode.KeepAliveReply parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static bit.workflowScheduler.grpc.scheduler_controller.gencode.KeepAliveReply parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static bit.workflowScheduler.grpc.scheduler_controller.gencode.KeepAliveReply parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static bit.workflowScheduler.grpc.scheduler_controller.gencode.KeepAliveReply parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static bit.workflowScheduler.grpc.scheduler_controller.gencode.KeepAliveReply parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static bit.workflowScheduler.grpc.scheduler_controller.gencode.KeepAliveReply parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static bit.workflowScheduler.grpc.scheduler_controller.gencode.KeepAliveReply parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static bit.workflowScheduler.grpc.scheduler_controller.gencode.KeepAliveReply parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static bit.workflowScheduler.grpc.scheduler_controller.gencode.KeepAliveReply parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(bit.workflowScheduler.grpc.scheduler_controller.gencode.KeepAliveReply prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code bit.workflowScheduler.grpc.scheduler_controller.gencode.KeepAliveReply}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:bit.workflowScheduler.grpc.scheduler_controller.gencode.KeepAliveReply)
      bit.workflowScheduler.grpc.scheduler_controller.gencode.KeepAliveReplyOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return bit.workflowScheduler.grpc.scheduler_controller.gencode.SchedulerControllerOuterClass.internal_static_bit_workflowScheduler_grpc_scheduler_controller_gencode_KeepAliveReply_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return bit.workflowScheduler.grpc.scheduler_controller.gencode.SchedulerControllerOuterClass.internal_static_bit_workflowScheduler_grpc_scheduler_controller_gencode_KeepAliveReply_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              bit.workflowScheduler.grpc.scheduler_controller.gencode.KeepAliveReply.class, bit.workflowScheduler.grpc.scheduler_controller.gencode.KeepAliveReply.Builder.class);
    }

    // Construct using bit.workflowScheduler.grpc.scheduler_controller.gencode.KeepAliveReply.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      waitSecs_ = 0;

      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return bit.workflowScheduler.grpc.scheduler_controller.gencode.SchedulerControllerOuterClass.internal_static_bit_workflowScheduler_grpc_scheduler_controller_gencode_KeepAliveReply_descriptor;
    }

    public bit.workflowScheduler.grpc.scheduler_controller.gencode.KeepAliveReply getDefaultInstanceForType() {
      return bit.workflowScheduler.grpc.scheduler_controller.gencode.KeepAliveReply.getDefaultInstance();
    }

    public bit.workflowScheduler.grpc.scheduler_controller.gencode.KeepAliveReply build() {
      bit.workflowScheduler.grpc.scheduler_controller.gencode.KeepAliveReply result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public bit.workflowScheduler.grpc.scheduler_controller.gencode.KeepAliveReply buildPartial() {
      bit.workflowScheduler.grpc.scheduler_controller.gencode.KeepAliveReply result = new bit.workflowScheduler.grpc.scheduler_controller.gencode.KeepAliveReply(this);
      result.waitSecs_ = waitSecs_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof bit.workflowScheduler.grpc.scheduler_controller.gencode.KeepAliveReply) {
        return mergeFrom((bit.workflowScheduler.grpc.scheduler_controller.gencode.KeepAliveReply)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(bit.workflowScheduler.grpc.scheduler_controller.gencode.KeepAliveReply other) {
      if (other == bit.workflowScheduler.grpc.scheduler_controller.gencode.KeepAliveReply.getDefaultInstance()) return this;
      if (other.getWaitSecs() != 0) {
        setWaitSecs(other.getWaitSecs());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      bit.workflowScheduler.grpc.scheduler_controller.gencode.KeepAliveReply parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (bit.workflowScheduler.grpc.scheduler_controller.gencode.KeepAliveReply) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private int waitSecs_ ;
    /**
     * <pre>
     * 下一次发送保活信号等待时间(从收到此应答到再次发送保活信号的等待时间，单位：秒)
     * 不会小于 1 秒
     * </pre>
     *
     * <code>int32 wait_secs = 1;</code>
     */
    public int getWaitSecs() {
      return waitSecs_;
    }
    /**
     * <pre>
     * 下一次发送保活信号等待时间(从收到此应答到再次发送保活信号的等待时间，单位：秒)
     * 不会小于 1 秒
     * </pre>
     *
     * <code>int32 wait_secs = 1;</code>
     */
    public Builder setWaitSecs(int value) {
      
      waitSecs_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 下一次发送保活信号等待时间(从收到此应答到再次发送保活信号的等待时间，单位：秒)
     * 不会小于 1 秒
     * </pre>
     *
     * <code>int32 wait_secs = 1;</code>
     */
    public Builder clearWaitSecs() {
      
      waitSecs_ = 0;
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:bit.workflowScheduler.grpc.scheduler_controller.gencode.KeepAliveReply)
  }

  // @@protoc_insertion_point(class_scope:bit.workflowScheduler.grpc.scheduler_controller.gencode.KeepAliveReply)
  private static final bit.workflowScheduler.grpc.scheduler_controller.gencode.KeepAliveReply DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new bit.workflowScheduler.grpc.scheduler_controller.gencode.KeepAliveReply();
  }

  public static bit.workflowScheduler.grpc.scheduler_controller.gencode.KeepAliveReply getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<KeepAliveReply>
      PARSER = new com.google.protobuf.AbstractParser<KeepAliveReply>() {
    public KeepAliveReply parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new KeepAliveReply(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<KeepAliveReply> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<KeepAliveReply> getParserForType() {
    return PARSER;
  }

  public bit.workflowScheduler.grpc.scheduler_controller.gencode.KeepAliveReply getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

