// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: TaskStatusTracker.proto

package bit.workflowScheduler.grpc.TaskStatusTracker.gencode;

public final class TaskStatusTrackerOuterClass {
  private TaskStatusTrackerOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_bit_workflowScheduler_grpc_TaskStatusTracker_gencode_TaskStateRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_bit_workflowScheduler_grpc_TaskStatusTracker_gencode_TaskStateRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_bit_workflowScheduler_grpc_TaskStatusTracker_gencode_TaskStateRequest_NodesState_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_bit_workflowScheduler_grpc_TaskStatusTracker_gencode_TaskStateRequest_NodesState_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_bit_workflowScheduler_grpc_TaskStatusTracker_gencode_TaskStateReply_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_bit_workflowScheduler_grpc_TaskStatusTracker_gencode_TaskStateReply_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\027TaskStatusTracker.proto\0224bit.workflowS" +
      "cheduler.grpc.TaskStatusTracker.gencode\"" +
      "\336\001\n\020TaskStateRequest\022\022\n\nworkflowID\030\001 \001(\t" +
      "\022d\n\tnodeState\030\002 \003(\0132Q.bit.workflowSchedu" +
      "ler.grpc.TaskStatusTracker.gencode.TaskS" +
      "tateRequest.NodesState\022\n\n\002IP\030\003 \001(\t\032D\n\nNo" +
      "desState\022\016\n\006taskID\030\001 \001(\r\022\023\n\013taskPodName\030" +
      "\002 \001(\t\022\021\n\ttaskState\030\003 \001(\t\" \n\016TaskStateRep" +
      "ly\022\016\n\006accept\030\001 \001(\r2\264\001\n\021TaskStatusTracker" +
      "\022\236\001\n\016InputTaskState\022F.bit.workflowSchedu" +
      "ler.grpc.TaskStatusTracker.gencode.TaskS" +
      "tateRequest\032D.bit.workflowScheduler.grpc" +
      ".TaskStatusTracker.gencode.TaskStateRepl" +
      "yB\002P\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_bit_workflowScheduler_grpc_TaskStatusTracker_gencode_TaskStateRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_bit_workflowScheduler_grpc_TaskStatusTracker_gencode_TaskStateRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_bit_workflowScheduler_grpc_TaskStatusTracker_gencode_TaskStateRequest_descriptor,
        new java.lang.String[] { "WorkflowID", "NodeState", "IP", });
    internal_static_bit_workflowScheduler_grpc_TaskStatusTracker_gencode_TaskStateRequest_NodesState_descriptor =
      internal_static_bit_workflowScheduler_grpc_TaskStatusTracker_gencode_TaskStateRequest_descriptor.getNestedTypes().get(0);
    internal_static_bit_workflowScheduler_grpc_TaskStatusTracker_gencode_TaskStateRequest_NodesState_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_bit_workflowScheduler_grpc_TaskStatusTracker_gencode_TaskStateRequest_NodesState_descriptor,
        new java.lang.String[] { "TaskID", "TaskPodName", "TaskState", });
    internal_static_bit_workflowScheduler_grpc_TaskStatusTracker_gencode_TaskStateReply_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_bit_workflowScheduler_grpc_TaskStatusTracker_gencode_TaskStateReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_bit_workflowScheduler_grpc_TaskStatusTracker_gencode_TaskStateReply_descriptor,
        new java.lang.String[] { "Accept", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
