// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: TaskStatusTracker.proto

package bit.workflowScheduler.grpc.TaskStatusTracker.gencode;

/**
 * Protobuf type {@code bit.workflowScheduler.grpc.TaskStatusTracker.gencode.TaskStateRequest}
 */
public  final class TaskStateRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:bit.workflowScheduler.grpc.TaskStatusTracker.gencode.TaskStateRequest)
    TaskStateRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use TaskStateRequest.newBuilder() to construct.
  private TaskStateRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private TaskStateRequest() {
    workflowID_ = "";
    nodeState_ = java.util.Collections.emptyList();
    iP_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private TaskStateRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            workflowID_ = s;
            break;
          }
          case 18: {
            if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
              nodeState_ = new java.util.ArrayList<bit.workflowScheduler.grpc.TaskStatusTracker.gencode.TaskStateRequest.NodesState>();
              mutable_bitField0_ |= 0x00000002;
            }
            nodeState_.add(
                input.readMessage(bit.workflowScheduler.grpc.TaskStatusTracker.gencode.TaskStateRequest.NodesState.parser(), extensionRegistry));
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            iP_ = s;
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
        nodeState_ = java.util.Collections.unmodifiableList(nodeState_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return bit.workflowScheduler.grpc.TaskStatusTracker.gencode.TaskStatusTrackerOuterClass.internal_static_bit_workflowScheduler_grpc_TaskStatusTracker_gencode_TaskStateRequest_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return bit.workflowScheduler.grpc.TaskStatusTracker.gencode.TaskStatusTrackerOuterClass.internal_static_bit_workflowScheduler_grpc_TaskStatusTracker_gencode_TaskStateRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            bit.workflowScheduler.grpc.TaskStatusTracker.gencode.TaskStateRequest.class, bit.workflowScheduler.grpc.TaskStatusTracker.gencode.TaskStateRequest.Builder.class);
  }

  public interface NodesStateOrBuilder extends
      // @@protoc_insertion_point(interface_extends:bit.workflowScheduler.grpc.TaskStatusTracker.gencode.TaskStateRequest.NodesState)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>uint32 taskID = 1;</code>
     */
    int getTaskID();

    /**
     * <pre>
     *例如task12-XX-XX. X个数不确定
     * </pre>
     *
     * <code>string taskPodName = 2;</code>
     */
    java.lang.String getTaskPodName();
    /**
     * <pre>
     *例如task12-XX-XX. X个数不确定
     * </pre>
     *
     * <code>string taskPodName = 2;</code>
     */
    com.google.protobuf.ByteString
        getTaskPodNameBytes();

    /**
     * <code>string taskState = 3;</code>
     */
    java.lang.String getTaskState();
    /**
     * <code>string taskState = 3;</code>
     */
    com.google.protobuf.ByteString
        getTaskStateBytes();
  }
  /**
   * Protobuf type {@code bit.workflowScheduler.grpc.TaskStatusTracker.gencode.TaskStateRequest.NodesState}
   */
  public  static final class NodesState extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:bit.workflowScheduler.grpc.TaskStatusTracker.gencode.TaskStateRequest.NodesState)
      NodesStateOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use NodesState.newBuilder() to construct.
    private NodesState(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private NodesState() {
      taskID_ = 0;
      taskPodName_ = "";
      taskState_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private NodesState(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              taskID_ = input.readUInt32();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              taskPodName_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              taskState_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return bit.workflowScheduler.grpc.TaskStatusTracker.gencode.TaskStatusTrackerOuterClass.internal_static_bit_workflowScheduler_grpc_TaskStatusTracker_gencode_TaskStateRequest_NodesState_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return bit.workflowScheduler.grpc.TaskStatusTracker.gencode.TaskStatusTrackerOuterClass.internal_static_bit_workflowScheduler_grpc_TaskStatusTracker_gencode_TaskStateRequest_NodesState_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              bit.workflowScheduler.grpc.TaskStatusTracker.gencode.TaskStateRequest.NodesState.class, bit.workflowScheduler.grpc.TaskStatusTracker.gencode.TaskStateRequest.NodesState.Builder.class);
    }

    public static final int TASKID_FIELD_NUMBER = 1;
    private int taskID_;
    /**
     * <code>uint32 taskID = 1;</code>
     */
    public int getTaskID() {
      return taskID_;
    }

    public static final int TASKPODNAME_FIELD_NUMBER = 2;
    private volatile java.lang.Object taskPodName_;
    /**
     * <pre>
     *例如task12-XX-XX. X个数不确定
     * </pre>
     *
     * <code>string taskPodName = 2;</code>
     */
    public java.lang.String getTaskPodName() {
      java.lang.Object ref = taskPodName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        taskPodName_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *例如task12-XX-XX. X个数不确定
     * </pre>
     *
     * <code>string taskPodName = 2;</code>
     */
    public com.google.protobuf.ByteString
        getTaskPodNameBytes() {
      java.lang.Object ref = taskPodName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        taskPodName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TASKSTATE_FIELD_NUMBER = 3;
    private volatile java.lang.Object taskState_;
    /**
     * <code>string taskState = 3;</code>
     */
    public java.lang.String getTaskState() {
      java.lang.Object ref = taskState_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        taskState_ = s;
        return s;
      }
    }
    /**
     * <code>string taskState = 3;</code>
     */
    public com.google.protobuf.ByteString
        getTaskStateBytes() {
      java.lang.Object ref = taskState_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        taskState_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (taskID_ != 0) {
        output.writeUInt32(1, taskID_);
      }
      if (!getTaskPodNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, taskPodName_);
      }
      if (!getTaskStateBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, taskState_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (taskID_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(1, taskID_);
      }
      if (!getTaskPodNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, taskPodName_);
      }
      if (!getTaskStateBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, taskState_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof bit.workflowScheduler.grpc.TaskStatusTracker.gencode.TaskStateRequest.NodesState)) {
        return super.equals(obj);
      }
      bit.workflowScheduler.grpc.TaskStatusTracker.gencode.TaskStateRequest.NodesState other = (bit.workflowScheduler.grpc.TaskStatusTracker.gencode.TaskStateRequest.NodesState) obj;

      boolean result = true;
      result = result && (getTaskID()
          == other.getTaskID());
      result = result && getTaskPodName()
          .equals(other.getTaskPodName());
      result = result && getTaskState()
          .equals(other.getTaskState());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + TASKID_FIELD_NUMBER;
      hash = (53 * hash) + getTaskID();
      hash = (37 * hash) + TASKPODNAME_FIELD_NUMBER;
      hash = (53 * hash) + getTaskPodName().hashCode();
      hash = (37 * hash) + TASKSTATE_FIELD_NUMBER;
      hash = (53 * hash) + getTaskState().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static bit.workflowScheduler.grpc.TaskStatusTracker.gencode.TaskStateRequest.NodesState parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static bit.workflowScheduler.grpc.TaskStatusTracker.gencode.TaskStateRequest.NodesState parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static bit.workflowScheduler.grpc.TaskStatusTracker.gencode.TaskStateRequest.NodesState parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static bit.workflowScheduler.grpc.TaskStatusTracker.gencode.TaskStateRequest.NodesState parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static bit.workflowScheduler.grpc.TaskStatusTracker.gencode.TaskStateRequest.NodesState parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static bit.workflowScheduler.grpc.TaskStatusTracker.gencode.TaskStateRequest.NodesState parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static bit.workflowScheduler.grpc.TaskStatusTracker.gencode.TaskStateRequest.NodesState parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static bit.workflowScheduler.grpc.TaskStatusTracker.gencode.TaskStateRequest.NodesState parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static bit.workflowScheduler.grpc.TaskStatusTracker.gencode.TaskStateRequest.NodesState parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static bit.workflowScheduler.grpc.TaskStatusTracker.gencode.TaskStateRequest.NodesState parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static bit.workflowScheduler.grpc.TaskStatusTracker.gencode.TaskStateRequest.NodesState parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static bit.workflowScheduler.grpc.TaskStatusTracker.gencode.TaskStateRequest.NodesState parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(bit.workflowScheduler.grpc.TaskStatusTracker.gencode.TaskStateRequest.NodesState prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code bit.workflowScheduler.grpc.TaskStatusTracker.gencode.TaskStateRequest.NodesState}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:bit.workflowScheduler.grpc.TaskStatusTracker.gencode.TaskStateRequest.NodesState)
        bit.workflowScheduler.grpc.TaskStatusTracker.gencode.TaskStateRequest.NodesStateOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return bit.workflowScheduler.grpc.TaskStatusTracker.gencode.TaskStatusTrackerOuterClass.internal_static_bit_workflowScheduler_grpc_TaskStatusTracker_gencode_TaskStateRequest_NodesState_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return bit.workflowScheduler.grpc.TaskStatusTracker.gencode.TaskStatusTrackerOuterClass.internal_static_bit_workflowScheduler_grpc_TaskStatusTracker_gencode_TaskStateRequest_NodesState_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                bit.workflowScheduler.grpc.TaskStatusTracker.gencode.TaskStateRequest.NodesState.class, bit.workflowScheduler.grpc.TaskStatusTracker.gencode.TaskStateRequest.NodesState.Builder.class);
      }

      // Construct using bit.workflowScheduler.grpc.TaskStatusTracker.gencode.TaskStateRequest.NodesState.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        taskID_ = 0;

        taskPodName_ = "";

        taskState_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return bit.workflowScheduler.grpc.TaskStatusTracker.gencode.TaskStatusTrackerOuterClass.internal_static_bit_workflowScheduler_grpc_TaskStatusTracker_gencode_TaskStateRequest_NodesState_descriptor;
      }

      public bit.workflowScheduler.grpc.TaskStatusTracker.gencode.TaskStateRequest.NodesState getDefaultInstanceForType() {
        return bit.workflowScheduler.grpc.TaskStatusTracker.gencode.TaskStateRequest.NodesState.getDefaultInstance();
      }

      public bit.workflowScheduler.grpc.TaskStatusTracker.gencode.TaskStateRequest.NodesState build() {
        bit.workflowScheduler.grpc.TaskStatusTracker.gencode.TaskStateRequest.NodesState result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public bit.workflowScheduler.grpc.TaskStatusTracker.gencode.TaskStateRequest.NodesState buildPartial() {
        bit.workflowScheduler.grpc.TaskStatusTracker.gencode.TaskStateRequest.NodesState result = new bit.workflowScheduler.grpc.TaskStatusTracker.gencode.TaskStateRequest.NodesState(this);
        result.taskID_ = taskID_;
        result.taskPodName_ = taskPodName_;
        result.taskState_ = taskState_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof bit.workflowScheduler.grpc.TaskStatusTracker.gencode.TaskStateRequest.NodesState) {
          return mergeFrom((bit.workflowScheduler.grpc.TaskStatusTracker.gencode.TaskStateRequest.NodesState)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(bit.workflowScheduler.grpc.TaskStatusTracker.gencode.TaskStateRequest.NodesState other) {
        if (other == bit.workflowScheduler.grpc.TaskStatusTracker.gencode.TaskStateRequest.NodesState.getDefaultInstance()) return this;
        if (other.getTaskID() != 0) {
          setTaskID(other.getTaskID());
        }
        if (!other.getTaskPodName().isEmpty()) {
          taskPodName_ = other.taskPodName_;
          onChanged();
        }
        if (!other.getTaskState().isEmpty()) {
          taskState_ = other.taskState_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        bit.workflowScheduler.grpc.TaskStatusTracker.gencode.TaskStateRequest.NodesState parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (bit.workflowScheduler.grpc.TaskStatusTracker.gencode.TaskStateRequest.NodesState) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int taskID_ ;
      /**
       * <code>uint32 taskID = 1;</code>
       */
      public int getTaskID() {
        return taskID_;
      }
      /**
       * <code>uint32 taskID = 1;</code>
       */
      public Builder setTaskID(int value) {
        
        taskID_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 taskID = 1;</code>
       */
      public Builder clearTaskID() {
        
        taskID_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object taskPodName_ = "";
      /**
       * <pre>
       *例如task12-XX-XX. X个数不确定
       * </pre>
       *
       * <code>string taskPodName = 2;</code>
       */
      public java.lang.String getTaskPodName() {
        java.lang.Object ref = taskPodName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          taskPodName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *例如task12-XX-XX. X个数不确定
       * </pre>
       *
       * <code>string taskPodName = 2;</code>
       */
      public com.google.protobuf.ByteString
          getTaskPodNameBytes() {
        java.lang.Object ref = taskPodName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          taskPodName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *例如task12-XX-XX. X个数不确定
       * </pre>
       *
       * <code>string taskPodName = 2;</code>
       */
      public Builder setTaskPodName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        taskPodName_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *例如task12-XX-XX. X个数不确定
       * </pre>
       *
       * <code>string taskPodName = 2;</code>
       */
      public Builder clearTaskPodName() {
        
        taskPodName_ = getDefaultInstance().getTaskPodName();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *例如task12-XX-XX. X个数不确定
       * </pre>
       *
       * <code>string taskPodName = 2;</code>
       */
      public Builder setTaskPodNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        taskPodName_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object taskState_ = "";
      /**
       * <code>string taskState = 3;</code>
       */
      public java.lang.String getTaskState() {
        java.lang.Object ref = taskState_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          taskState_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string taskState = 3;</code>
       */
      public com.google.protobuf.ByteString
          getTaskStateBytes() {
        java.lang.Object ref = taskState_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          taskState_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string taskState = 3;</code>
       */
      public Builder setTaskState(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        taskState_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string taskState = 3;</code>
       */
      public Builder clearTaskState() {
        
        taskState_ = getDefaultInstance().getTaskState();
        onChanged();
        return this;
      }
      /**
       * <code>string taskState = 3;</code>
       */
      public Builder setTaskStateBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        taskState_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:bit.workflowScheduler.grpc.TaskStatusTracker.gencode.TaskStateRequest.NodesState)
    }

    // @@protoc_insertion_point(class_scope:bit.workflowScheduler.grpc.TaskStatusTracker.gencode.TaskStateRequest.NodesState)
    private static final bit.workflowScheduler.grpc.TaskStatusTracker.gencode.TaskStateRequest.NodesState DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new bit.workflowScheduler.grpc.TaskStatusTracker.gencode.TaskStateRequest.NodesState();
    }

    public static bit.workflowScheduler.grpc.TaskStatusTracker.gencode.TaskStateRequest.NodesState getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<NodesState>
        PARSER = new com.google.protobuf.AbstractParser<NodesState>() {
      public NodesState parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new NodesState(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<NodesState> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<NodesState> getParserForType() {
      return PARSER;
    }

    public bit.workflowScheduler.grpc.TaskStatusTracker.gencode.TaskStateRequest.NodesState getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private int bitField0_;
  public static final int WORKFLOWID_FIELD_NUMBER = 1;
  private volatile java.lang.Object workflowID_;
  /**
   * <pre>
   *workflowXX, 查询时将直接其作为namespace
   * </pre>
   *
   * <code>string workflowID = 1;</code>
   */
  public java.lang.String getWorkflowID() {
    java.lang.Object ref = workflowID_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      workflowID_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *workflowXX, 查询时将直接其作为namespace
   * </pre>
   *
   * <code>string workflowID = 1;</code>
   */
  public com.google.protobuf.ByteString
      getWorkflowIDBytes() {
    java.lang.Object ref = workflowID_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      workflowID_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int NODESTATE_FIELD_NUMBER = 2;
  private java.util.List<bit.workflowScheduler.grpc.TaskStatusTracker.gencode.TaskStateRequest.NodesState> nodeState_;
  /**
   * <code>repeated .bit.workflowScheduler.grpc.TaskStatusTracker.gencode.TaskStateRequest.NodesState nodeState = 2;</code>
   */
  public java.util.List<bit.workflowScheduler.grpc.TaskStatusTracker.gencode.TaskStateRequest.NodesState> getNodeStateList() {
    return nodeState_;
  }
  /**
   * <code>repeated .bit.workflowScheduler.grpc.TaskStatusTracker.gencode.TaskStateRequest.NodesState nodeState = 2;</code>
   */
  public java.util.List<? extends bit.workflowScheduler.grpc.TaskStatusTracker.gencode.TaskStateRequest.NodesStateOrBuilder> 
      getNodeStateOrBuilderList() {
    return nodeState_;
  }
  /**
   * <code>repeated .bit.workflowScheduler.grpc.TaskStatusTracker.gencode.TaskStateRequest.NodesState nodeState = 2;</code>
   */
  public int getNodeStateCount() {
    return nodeState_.size();
  }
  /**
   * <code>repeated .bit.workflowScheduler.grpc.TaskStatusTracker.gencode.TaskStateRequest.NodesState nodeState = 2;</code>
   */
  public bit.workflowScheduler.grpc.TaskStatusTracker.gencode.TaskStateRequest.NodesState getNodeState(int index) {
    return nodeState_.get(index);
  }
  /**
   * <code>repeated .bit.workflowScheduler.grpc.TaskStatusTracker.gencode.TaskStateRequest.NodesState nodeState = 2;</code>
   */
  public bit.workflowScheduler.grpc.TaskStatusTracker.gencode.TaskStateRequest.NodesStateOrBuilder getNodeStateOrBuilder(
      int index) {
    return nodeState_.get(index);
  }

  public static final int IP_FIELD_NUMBER = 3;
  private volatile java.lang.Object iP_;
  /**
   * <pre>
   *调度器所在的IP
   * </pre>
   *
   * <code>string IP = 3;</code>
   */
  public java.lang.String getIP() {
    java.lang.Object ref = iP_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      iP_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *调度器所在的IP
   * </pre>
   *
   * <code>string IP = 3;</code>
   */
  public com.google.protobuf.ByteString
      getIPBytes() {
    java.lang.Object ref = iP_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      iP_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getWorkflowIDBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, workflowID_);
    }
    for (int i = 0; i < nodeState_.size(); i++) {
      output.writeMessage(2, nodeState_.get(i));
    }
    if (!getIPBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, iP_);
    }
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getWorkflowIDBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, workflowID_);
    }
    for (int i = 0; i < nodeState_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, nodeState_.get(i));
    }
    if (!getIPBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, iP_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof bit.workflowScheduler.grpc.TaskStatusTracker.gencode.TaskStateRequest)) {
      return super.equals(obj);
    }
    bit.workflowScheduler.grpc.TaskStatusTracker.gencode.TaskStateRequest other = (bit.workflowScheduler.grpc.TaskStatusTracker.gencode.TaskStateRequest) obj;

    boolean result = true;
    result = result && getWorkflowID()
        .equals(other.getWorkflowID());
    result = result && getNodeStateList()
        .equals(other.getNodeStateList());
    result = result && getIP()
        .equals(other.getIP());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + WORKFLOWID_FIELD_NUMBER;
    hash = (53 * hash) + getWorkflowID().hashCode();
    if (getNodeStateCount() > 0) {
      hash = (37 * hash) + NODESTATE_FIELD_NUMBER;
      hash = (53 * hash) + getNodeStateList().hashCode();
    }
    hash = (37 * hash) + IP_FIELD_NUMBER;
    hash = (53 * hash) + getIP().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static bit.workflowScheduler.grpc.TaskStatusTracker.gencode.TaskStateRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static bit.workflowScheduler.grpc.TaskStatusTracker.gencode.TaskStateRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static bit.workflowScheduler.grpc.TaskStatusTracker.gencode.TaskStateRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static bit.workflowScheduler.grpc.TaskStatusTracker.gencode.TaskStateRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static bit.workflowScheduler.grpc.TaskStatusTracker.gencode.TaskStateRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static bit.workflowScheduler.grpc.TaskStatusTracker.gencode.TaskStateRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static bit.workflowScheduler.grpc.TaskStatusTracker.gencode.TaskStateRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static bit.workflowScheduler.grpc.TaskStatusTracker.gencode.TaskStateRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static bit.workflowScheduler.grpc.TaskStatusTracker.gencode.TaskStateRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static bit.workflowScheduler.grpc.TaskStatusTracker.gencode.TaskStateRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static bit.workflowScheduler.grpc.TaskStatusTracker.gencode.TaskStateRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static bit.workflowScheduler.grpc.TaskStatusTracker.gencode.TaskStateRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(bit.workflowScheduler.grpc.TaskStatusTracker.gencode.TaskStateRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code bit.workflowScheduler.grpc.TaskStatusTracker.gencode.TaskStateRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:bit.workflowScheduler.grpc.TaskStatusTracker.gencode.TaskStateRequest)
      bit.workflowScheduler.grpc.TaskStatusTracker.gencode.TaskStateRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return bit.workflowScheduler.grpc.TaskStatusTracker.gencode.TaskStatusTrackerOuterClass.internal_static_bit_workflowScheduler_grpc_TaskStatusTracker_gencode_TaskStateRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return bit.workflowScheduler.grpc.TaskStatusTracker.gencode.TaskStatusTrackerOuterClass.internal_static_bit_workflowScheduler_grpc_TaskStatusTracker_gencode_TaskStateRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              bit.workflowScheduler.grpc.TaskStatusTracker.gencode.TaskStateRequest.class, bit.workflowScheduler.grpc.TaskStatusTracker.gencode.TaskStateRequest.Builder.class);
    }

    // Construct using bit.workflowScheduler.grpc.TaskStatusTracker.gencode.TaskStateRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getNodeStateFieldBuilder();
      }
    }
    public Builder clear() {
      super.clear();
      workflowID_ = "";

      if (nodeStateBuilder_ == null) {
        nodeState_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
      } else {
        nodeStateBuilder_.clear();
      }
      iP_ = "";

      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return bit.workflowScheduler.grpc.TaskStatusTracker.gencode.TaskStatusTrackerOuterClass.internal_static_bit_workflowScheduler_grpc_TaskStatusTracker_gencode_TaskStateRequest_descriptor;
    }

    public bit.workflowScheduler.grpc.TaskStatusTracker.gencode.TaskStateRequest getDefaultInstanceForType() {
      return bit.workflowScheduler.grpc.TaskStatusTracker.gencode.TaskStateRequest.getDefaultInstance();
    }

    public bit.workflowScheduler.grpc.TaskStatusTracker.gencode.TaskStateRequest build() {
      bit.workflowScheduler.grpc.TaskStatusTracker.gencode.TaskStateRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public bit.workflowScheduler.grpc.TaskStatusTracker.gencode.TaskStateRequest buildPartial() {
      bit.workflowScheduler.grpc.TaskStatusTracker.gencode.TaskStateRequest result = new bit.workflowScheduler.grpc.TaskStatusTracker.gencode.TaskStateRequest(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      result.workflowID_ = workflowID_;
      if (nodeStateBuilder_ == null) {
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          nodeState_ = java.util.Collections.unmodifiableList(nodeState_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.nodeState_ = nodeState_;
      } else {
        result.nodeState_ = nodeStateBuilder_.build();
      }
      result.iP_ = iP_;
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof bit.workflowScheduler.grpc.TaskStatusTracker.gencode.TaskStateRequest) {
        return mergeFrom((bit.workflowScheduler.grpc.TaskStatusTracker.gencode.TaskStateRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(bit.workflowScheduler.grpc.TaskStatusTracker.gencode.TaskStateRequest other) {
      if (other == bit.workflowScheduler.grpc.TaskStatusTracker.gencode.TaskStateRequest.getDefaultInstance()) return this;
      if (!other.getWorkflowID().isEmpty()) {
        workflowID_ = other.workflowID_;
        onChanged();
      }
      if (nodeStateBuilder_ == null) {
        if (!other.nodeState_.isEmpty()) {
          if (nodeState_.isEmpty()) {
            nodeState_ = other.nodeState_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureNodeStateIsMutable();
            nodeState_.addAll(other.nodeState_);
          }
          onChanged();
        }
      } else {
        if (!other.nodeState_.isEmpty()) {
          if (nodeStateBuilder_.isEmpty()) {
            nodeStateBuilder_.dispose();
            nodeStateBuilder_ = null;
            nodeState_ = other.nodeState_;
            bitField0_ = (bitField0_ & ~0x00000002);
            nodeStateBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getNodeStateFieldBuilder() : null;
          } else {
            nodeStateBuilder_.addAllMessages(other.nodeState_);
          }
        }
      }
      if (!other.getIP().isEmpty()) {
        iP_ = other.iP_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      bit.workflowScheduler.grpc.TaskStatusTracker.gencode.TaskStateRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (bit.workflowScheduler.grpc.TaskStatusTracker.gencode.TaskStateRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.lang.Object workflowID_ = "";
    /**
     * <pre>
     *workflowXX, 查询时将直接其作为namespace
     * </pre>
     *
     * <code>string workflowID = 1;</code>
     */
    public java.lang.String getWorkflowID() {
      java.lang.Object ref = workflowID_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        workflowID_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     *workflowXX, 查询时将直接其作为namespace
     * </pre>
     *
     * <code>string workflowID = 1;</code>
     */
    public com.google.protobuf.ByteString
        getWorkflowIDBytes() {
      java.lang.Object ref = workflowID_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        workflowID_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *workflowXX, 查询时将直接其作为namespace
     * </pre>
     *
     * <code>string workflowID = 1;</code>
     */
    public Builder setWorkflowID(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      workflowID_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *workflowXX, 查询时将直接其作为namespace
     * </pre>
     *
     * <code>string workflowID = 1;</code>
     */
    public Builder clearWorkflowID() {
      
      workflowID_ = getDefaultInstance().getWorkflowID();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *workflowXX, 查询时将直接其作为namespace
     * </pre>
     *
     * <code>string workflowID = 1;</code>
     */
    public Builder setWorkflowIDBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      workflowID_ = value;
      onChanged();
      return this;
    }

    private java.util.List<bit.workflowScheduler.grpc.TaskStatusTracker.gencode.TaskStateRequest.NodesState> nodeState_ =
      java.util.Collections.emptyList();
    private void ensureNodeStateIsMutable() {
      if (!((bitField0_ & 0x00000002) == 0x00000002)) {
        nodeState_ = new java.util.ArrayList<bit.workflowScheduler.grpc.TaskStatusTracker.gencode.TaskStateRequest.NodesState>(nodeState_);
        bitField0_ |= 0x00000002;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        bit.workflowScheduler.grpc.TaskStatusTracker.gencode.TaskStateRequest.NodesState, bit.workflowScheduler.grpc.TaskStatusTracker.gencode.TaskStateRequest.NodesState.Builder, bit.workflowScheduler.grpc.TaskStatusTracker.gencode.TaskStateRequest.NodesStateOrBuilder> nodeStateBuilder_;

    /**
     * <code>repeated .bit.workflowScheduler.grpc.TaskStatusTracker.gencode.TaskStateRequest.NodesState nodeState = 2;</code>
     */
    public java.util.List<bit.workflowScheduler.grpc.TaskStatusTracker.gencode.TaskStateRequest.NodesState> getNodeStateList() {
      if (nodeStateBuilder_ == null) {
        return java.util.Collections.unmodifiableList(nodeState_);
      } else {
        return nodeStateBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .bit.workflowScheduler.grpc.TaskStatusTracker.gencode.TaskStateRequest.NodesState nodeState = 2;</code>
     */
    public int getNodeStateCount() {
      if (nodeStateBuilder_ == null) {
        return nodeState_.size();
      } else {
        return nodeStateBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .bit.workflowScheduler.grpc.TaskStatusTracker.gencode.TaskStateRequest.NodesState nodeState = 2;</code>
     */
    public bit.workflowScheduler.grpc.TaskStatusTracker.gencode.TaskStateRequest.NodesState getNodeState(int index) {
      if (nodeStateBuilder_ == null) {
        return nodeState_.get(index);
      } else {
        return nodeStateBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .bit.workflowScheduler.grpc.TaskStatusTracker.gencode.TaskStateRequest.NodesState nodeState = 2;</code>
     */
    public Builder setNodeState(
        int index, bit.workflowScheduler.grpc.TaskStatusTracker.gencode.TaskStateRequest.NodesState value) {
      if (nodeStateBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureNodeStateIsMutable();
        nodeState_.set(index, value);
        onChanged();
      } else {
        nodeStateBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .bit.workflowScheduler.grpc.TaskStatusTracker.gencode.TaskStateRequest.NodesState nodeState = 2;</code>
     */
    public Builder setNodeState(
        int index, bit.workflowScheduler.grpc.TaskStatusTracker.gencode.TaskStateRequest.NodesState.Builder builderForValue) {
      if (nodeStateBuilder_ == null) {
        ensureNodeStateIsMutable();
        nodeState_.set(index, builderForValue.build());
        onChanged();
      } else {
        nodeStateBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .bit.workflowScheduler.grpc.TaskStatusTracker.gencode.TaskStateRequest.NodesState nodeState = 2;</code>
     */
    public Builder addNodeState(bit.workflowScheduler.grpc.TaskStatusTracker.gencode.TaskStateRequest.NodesState value) {
      if (nodeStateBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureNodeStateIsMutable();
        nodeState_.add(value);
        onChanged();
      } else {
        nodeStateBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .bit.workflowScheduler.grpc.TaskStatusTracker.gencode.TaskStateRequest.NodesState nodeState = 2;</code>
     */
    public Builder addNodeState(
        int index, bit.workflowScheduler.grpc.TaskStatusTracker.gencode.TaskStateRequest.NodesState value) {
      if (nodeStateBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureNodeStateIsMutable();
        nodeState_.add(index, value);
        onChanged();
      } else {
        nodeStateBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .bit.workflowScheduler.grpc.TaskStatusTracker.gencode.TaskStateRequest.NodesState nodeState = 2;</code>
     */
    public Builder addNodeState(
        bit.workflowScheduler.grpc.TaskStatusTracker.gencode.TaskStateRequest.NodesState.Builder builderForValue) {
      if (nodeStateBuilder_ == null) {
        ensureNodeStateIsMutable();
        nodeState_.add(builderForValue.build());
        onChanged();
      } else {
        nodeStateBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .bit.workflowScheduler.grpc.TaskStatusTracker.gencode.TaskStateRequest.NodesState nodeState = 2;</code>
     */
    public Builder addNodeState(
        int index, bit.workflowScheduler.grpc.TaskStatusTracker.gencode.TaskStateRequest.NodesState.Builder builderForValue) {
      if (nodeStateBuilder_ == null) {
        ensureNodeStateIsMutable();
        nodeState_.add(index, builderForValue.build());
        onChanged();
      } else {
        nodeStateBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .bit.workflowScheduler.grpc.TaskStatusTracker.gencode.TaskStateRequest.NodesState nodeState = 2;</code>
     */
    public Builder addAllNodeState(
        java.lang.Iterable<? extends bit.workflowScheduler.grpc.TaskStatusTracker.gencode.TaskStateRequest.NodesState> values) {
      if (nodeStateBuilder_ == null) {
        ensureNodeStateIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, nodeState_);
        onChanged();
      } else {
        nodeStateBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .bit.workflowScheduler.grpc.TaskStatusTracker.gencode.TaskStateRequest.NodesState nodeState = 2;</code>
     */
    public Builder clearNodeState() {
      if (nodeStateBuilder_ == null) {
        nodeState_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
      } else {
        nodeStateBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .bit.workflowScheduler.grpc.TaskStatusTracker.gencode.TaskStateRequest.NodesState nodeState = 2;</code>
     */
    public Builder removeNodeState(int index) {
      if (nodeStateBuilder_ == null) {
        ensureNodeStateIsMutable();
        nodeState_.remove(index);
        onChanged();
      } else {
        nodeStateBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .bit.workflowScheduler.grpc.TaskStatusTracker.gencode.TaskStateRequest.NodesState nodeState = 2;</code>
     */
    public bit.workflowScheduler.grpc.TaskStatusTracker.gencode.TaskStateRequest.NodesState.Builder getNodeStateBuilder(
        int index) {
      return getNodeStateFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .bit.workflowScheduler.grpc.TaskStatusTracker.gencode.TaskStateRequest.NodesState nodeState = 2;</code>
     */
    public bit.workflowScheduler.grpc.TaskStatusTracker.gencode.TaskStateRequest.NodesStateOrBuilder getNodeStateOrBuilder(
        int index) {
      if (nodeStateBuilder_ == null) {
        return nodeState_.get(index);  } else {
        return nodeStateBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .bit.workflowScheduler.grpc.TaskStatusTracker.gencode.TaskStateRequest.NodesState nodeState = 2;</code>
     */
    public java.util.List<? extends bit.workflowScheduler.grpc.TaskStatusTracker.gencode.TaskStateRequest.NodesStateOrBuilder> 
         getNodeStateOrBuilderList() {
      if (nodeStateBuilder_ != null) {
        return nodeStateBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(nodeState_);
      }
    }
    /**
     * <code>repeated .bit.workflowScheduler.grpc.TaskStatusTracker.gencode.TaskStateRequest.NodesState nodeState = 2;</code>
     */
    public bit.workflowScheduler.grpc.TaskStatusTracker.gencode.TaskStateRequest.NodesState.Builder addNodeStateBuilder() {
      return getNodeStateFieldBuilder().addBuilder(
          bit.workflowScheduler.grpc.TaskStatusTracker.gencode.TaskStateRequest.NodesState.getDefaultInstance());
    }
    /**
     * <code>repeated .bit.workflowScheduler.grpc.TaskStatusTracker.gencode.TaskStateRequest.NodesState nodeState = 2;</code>
     */
    public bit.workflowScheduler.grpc.TaskStatusTracker.gencode.TaskStateRequest.NodesState.Builder addNodeStateBuilder(
        int index) {
      return getNodeStateFieldBuilder().addBuilder(
          index, bit.workflowScheduler.grpc.TaskStatusTracker.gencode.TaskStateRequest.NodesState.getDefaultInstance());
    }
    /**
     * <code>repeated .bit.workflowScheduler.grpc.TaskStatusTracker.gencode.TaskStateRequest.NodesState nodeState = 2;</code>
     */
    public java.util.List<bit.workflowScheduler.grpc.TaskStatusTracker.gencode.TaskStateRequest.NodesState.Builder> 
         getNodeStateBuilderList() {
      return getNodeStateFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        bit.workflowScheduler.grpc.TaskStatusTracker.gencode.TaskStateRequest.NodesState, bit.workflowScheduler.grpc.TaskStatusTracker.gencode.TaskStateRequest.NodesState.Builder, bit.workflowScheduler.grpc.TaskStatusTracker.gencode.TaskStateRequest.NodesStateOrBuilder> 
        getNodeStateFieldBuilder() {
      if (nodeStateBuilder_ == null) {
        nodeStateBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            bit.workflowScheduler.grpc.TaskStatusTracker.gencode.TaskStateRequest.NodesState, bit.workflowScheduler.grpc.TaskStatusTracker.gencode.TaskStateRequest.NodesState.Builder, bit.workflowScheduler.grpc.TaskStatusTracker.gencode.TaskStateRequest.NodesStateOrBuilder>(
                nodeState_,
                ((bitField0_ & 0x00000002) == 0x00000002),
                getParentForChildren(),
                isClean());
        nodeState_ = null;
      }
      return nodeStateBuilder_;
    }

    private java.lang.Object iP_ = "";
    /**
     * <pre>
     *调度器所在的IP
     * </pre>
     *
     * <code>string IP = 3;</code>
     */
    public java.lang.String getIP() {
      java.lang.Object ref = iP_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        iP_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     *调度器所在的IP
     * </pre>
     *
     * <code>string IP = 3;</code>
     */
    public com.google.protobuf.ByteString
        getIPBytes() {
      java.lang.Object ref = iP_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        iP_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *调度器所在的IP
     * </pre>
     *
     * <code>string IP = 3;</code>
     */
    public Builder setIP(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      iP_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *调度器所在的IP
     * </pre>
     *
     * <code>string IP = 3;</code>
     */
    public Builder clearIP() {
      
      iP_ = getDefaultInstance().getIP();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *调度器所在的IP
     * </pre>
     *
     * <code>string IP = 3;</code>
     */
    public Builder setIPBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      iP_ = value;
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:bit.workflowScheduler.grpc.TaskStatusTracker.gencode.TaskStateRequest)
  }

  // @@protoc_insertion_point(class_scope:bit.workflowScheduler.grpc.TaskStatusTracker.gencode.TaskStateRequest)
  private static final bit.workflowScheduler.grpc.TaskStatusTracker.gencode.TaskStateRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new bit.workflowScheduler.grpc.TaskStatusTracker.gencode.TaskStateRequest();
  }

  public static bit.workflowScheduler.grpc.TaskStatusTracker.gencode.TaskStateRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<TaskStateRequest>
      PARSER = new com.google.protobuf.AbstractParser<TaskStateRequest>() {
    public TaskStateRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new TaskStateRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<TaskStateRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<TaskStateRequest> getParserForType() {
    return PARSER;
  }

  public bit.workflowScheduler.grpc.TaskStatusTracker.gencode.TaskStateRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

