// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: scheduler.proto

package bit.workflowScheduler.grpc.Scheduler.gencode;

public interface DeleteWorkflowRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:bit.workflowScheduler.grpc.Scheduler.gencode.DeleteWorkflowRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string workflow_id = 1;</code>
   */
  java.lang.String getWorkflowId();
  /**
   * <code>string workflow_id = 1;</code>
   */
  com.google.protobuf.ByteString
      getWorkflowIdBytes();

  /**
   * <code>string custom_id = 2;</code>
   */
  java.lang.String getCustomId();
  /**
   * <code>string custom_id = 2;</code>
   */
  com.google.protobuf.ByteString
      getCustomIdBytes();
}
