// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: scheduler.proto

package bit.workflowScheduler.grpc.Scheduler.gencode;

public final class SchedulerOuterClass {
  private SchedulerOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_bit_workflowScheduler_grpc_Scheduler_gencode_WorkflowTransferRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_bit_workflowScheduler_grpc_Scheduler_gencode_WorkflowTransferRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_bit_workflowScheduler_grpc_Scheduler_gencode_WorkflowTransferReply_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_bit_workflowScheduler_grpc_Scheduler_gencode_WorkflowTransferReply_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_bit_workflowScheduler_grpc_Scheduler_gencode_TaskStateRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_bit_workflowScheduler_grpc_Scheduler_gencode_TaskStateRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_bit_workflowScheduler_grpc_Scheduler_gencode_TaskStateRequest_NodesState_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_bit_workflowScheduler_grpc_Scheduler_gencode_TaskStateRequest_NodesState_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_bit_workflowScheduler_grpc_Scheduler_gencode_TaskStateReply_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_bit_workflowScheduler_grpc_Scheduler_gencode_TaskStateReply_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_bit_workflowScheduler_grpc_Scheduler_gencode_DeleteWorkflowRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_bit_workflowScheduler_grpc_Scheduler_gencode_DeleteWorkflowRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_bit_workflowScheduler_grpc_Scheduler_gencode_DeleteWorkflowReply_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_bit_workflowScheduler_grpc_Scheduler_gencode_DeleteWorkflowReply_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017scheduler.proto\022,bit.workflowScheduler" +
      ".grpc.Scheduler.gencode\"8\n\027WorkflowTrans" +
      "ferRequest\022\013\n\003sid\030\001 \001(\t\022\020\n\010workflow\030\002 \003(" +
      "\014\"\'\n\025WorkflowTransferReply\022\016\n\006accept\030\001 \001" +
      "(\r\"\326\001\n\020TaskStateRequest\022\022\n\nworkflowID\030\001 " +
      "\001(\t\022\\\n\tnodeState\030\002 \003(\0132I.bit.workflowSch" +
      "eduler.grpc.Scheduler.gencode.TaskStateR" +
      "equest.NodesState\022\n\n\002IP\030\003 \001(\t\032D\n\nNodesSt" +
      "ate\022\016\n\006taskID\030\001 \001(\r\022\023\n\013taskPodName\030\002 \001(\t" +
      "\022\021\n\ttaskState\030\003 \001(\t\" \n\016TaskStateReply\022\016\n" +
      "\006accept\030\001 \001(\r\"?\n\025DeleteWorkflowRequest\022\023" +
      "\n\013workflow_id\030\001 \001(\t\022\021\n\tcustom_id\030\002 \001(\t\"<" +
      "\n\023DeleteWorkflowReply\022\016\n\006result\030\001 \001(\r\022\025\n" +
      "\rerror_message\030\002 \001(\t2\330\003\n\tScheduler\022\236\001\n\020W" +
      "orkflowTransfer\022E.bit.workflowScheduler." +
      "grpc.Scheduler.gencode.WorkflowTransferR" +
      "equest\032C.bit.workflowScheduler.grpc.Sche" +
      "duler.gencode.WorkflowTransferReply\022\216\001\n\016" +
      "InputTaskState\022>.bit.workflowScheduler.g" +
      "rpc.Scheduler.gencode.TaskStateRequest\032<" +
      ".bit.workflowScheduler.grpc.Scheduler.ge" +
      "ncode.TaskStateReply\022\230\001\n\016DeleteWorkflow\022" +
      "C.bit.workflowScheduler.grpc.Scheduler.g" +
      "encode.DeleteWorkflowRequest\032A.bit.workf" +
      "lowScheduler.grpc.Scheduler.gencode.Dele" +
      "teWorkflowReplyB\002P\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_bit_workflowScheduler_grpc_Scheduler_gencode_WorkflowTransferRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_bit_workflowScheduler_grpc_Scheduler_gencode_WorkflowTransferRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_bit_workflowScheduler_grpc_Scheduler_gencode_WorkflowTransferRequest_descriptor,
        new java.lang.String[] { "Sid", "Workflow", });
    internal_static_bit_workflowScheduler_grpc_Scheduler_gencode_WorkflowTransferReply_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_bit_workflowScheduler_grpc_Scheduler_gencode_WorkflowTransferReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_bit_workflowScheduler_grpc_Scheduler_gencode_WorkflowTransferReply_descriptor,
        new java.lang.String[] { "Accept", });
    internal_static_bit_workflowScheduler_grpc_Scheduler_gencode_TaskStateRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_bit_workflowScheduler_grpc_Scheduler_gencode_TaskStateRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_bit_workflowScheduler_grpc_Scheduler_gencode_TaskStateRequest_descriptor,
        new java.lang.String[] { "WorkflowID", "NodeState", "IP", });
    internal_static_bit_workflowScheduler_grpc_Scheduler_gencode_TaskStateRequest_NodesState_descriptor =
      internal_static_bit_workflowScheduler_grpc_Scheduler_gencode_TaskStateRequest_descriptor.getNestedTypes().get(0);
    internal_static_bit_workflowScheduler_grpc_Scheduler_gencode_TaskStateRequest_NodesState_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_bit_workflowScheduler_grpc_Scheduler_gencode_TaskStateRequest_NodesState_descriptor,
        new java.lang.String[] { "TaskID", "TaskPodName", "TaskState", });
    internal_static_bit_workflowScheduler_grpc_Scheduler_gencode_TaskStateReply_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_bit_workflowScheduler_grpc_Scheduler_gencode_TaskStateReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_bit_workflowScheduler_grpc_Scheduler_gencode_TaskStateReply_descriptor,
        new java.lang.String[] { "Accept", });
    internal_static_bit_workflowScheduler_grpc_Scheduler_gencode_DeleteWorkflowRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_bit_workflowScheduler_grpc_Scheduler_gencode_DeleteWorkflowRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_bit_workflowScheduler_grpc_Scheduler_gencode_DeleteWorkflowRequest_descriptor,
        new java.lang.String[] { "WorkflowId", "CustomId", });
    internal_static_bit_workflowScheduler_grpc_Scheduler_gencode_DeleteWorkflowReply_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_bit_workflowScheduler_grpc_Scheduler_gencode_DeleteWorkflowReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_bit_workflowScheduler_grpc_Scheduler_gencode_DeleteWorkflowReply_descriptor,
        new java.lang.String[] { "Result", "ErrorMessage", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
