// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: scheduler.proto

package bit.workflowScheduler.grpc.Scheduler.gencode;

public interface WorkflowTransferReplyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:bit.workflowScheduler.grpc.Scheduler.gencode.WorkflowTransferReply)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 返回标记符，表示收到文件
   * </pre>
   *
   * <code>uint32 accept = 1;</code>
   */
  int getAccept();
}
