// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: resource_allocator.proto

package bit.workflowScheduler.grpc.resource_allocator.gencode;

public interface CreateSchedulerPodResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:bit.workflowScheduler.grpc.resource_allocator.gencode.CreateSchedulerPodResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *成功创建,根据当前剩余资源返回创建调度起pod的上限数 成功&gt;=1，失败置为0）
   * </pre>
   *
   * <code>int32 result = 1;</code>
   */
  int getResult();

  /**
   * <pre>
   *在失败状态下，可以设置状态码
   *成功状态（result&gt;=1），客户端不关系此字段，置为 0 即可
   * </pre>
   *
   * <code>int32 err_no = 2;</code>
   */
  int getErrNo();
}
