// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: resource_allocator.proto

package bit.workflowScheduler.grpc.resource_allocator.gencode;

/**
 * <pre>
 *请求创建任务POD
 * </pre>
 *
 * Protobuf type {@code bit.workflowScheduler.grpc.resource_allocator.gencode.CreateTaskPodRequest}
 */
public  final class CreateTaskPodRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:bit.workflowScheduler.grpc.resource_allocator.gencode.CreateTaskPodRequest)
    CreateTaskPodRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use CreateTaskPodRequest.newBuilder() to construct.
  private CreateTaskPodRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private CreateTaskPodRequest() {
    workflowId_ = "";
    taskName_ = "";
    image_ = "";
    cpu_ = 0L;
    mem_ = 0L;
    inputVector_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    outputVector_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    customization_ = false;
    timeGrade_ = false;
    costGrade_ = false;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private CreateTaskPodRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            workflowId_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            taskName_ = s;
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            image_ = s;
            break;
          }
          case 32: {

            cpu_ = input.readInt64();
            break;
          }
          case 40: {

            mem_ = input.readInt64();
            break;
          }
          case 50: {
            if (!((mutable_bitField0_ & 0x00000020) == 0x00000020)) {
              env_ = com.google.protobuf.MapField.newMapField(
                  EnvDefaultEntryHolder.defaultEntry);
              mutable_bitField0_ |= 0x00000020;
            }
            com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
            env__ = input.readMessage(
                EnvDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
            env_.getMutableMap().put(
                env__.getKey(), env__.getValue());
            break;
          }
          case 58: {
            java.lang.String s = input.readStringRequireUtf8();
            if (!((mutable_bitField0_ & 0x00000040) == 0x00000040)) {
              inputVector_ = new com.google.protobuf.LazyStringArrayList();
              mutable_bitField0_ |= 0x00000040;
            }
            inputVector_.add(s);
            break;
          }
          case 66: {
            java.lang.String s = input.readStringRequireUtf8();
            if (!((mutable_bitField0_ & 0x00000080) == 0x00000080)) {
              outputVector_ = new com.google.protobuf.LazyStringArrayList();
              mutable_bitField0_ |= 0x00000080;
            }
            outputVector_.add(s);
            break;
          }
          case 72: {

            customization_ = input.readBool();
            break;
          }
          case 80: {

            timeGrade_ = input.readBool();
            break;
          }
          case 88: {

            costGrade_ = input.readBool();
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000040) == 0x00000040)) {
        inputVector_ = inputVector_.getUnmodifiableView();
      }
      if (((mutable_bitField0_ & 0x00000080) == 0x00000080)) {
        outputVector_ = outputVector_.getUnmodifiableView();
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return bit.workflowScheduler.grpc.resource_allocator.gencode.ResourceAllocator.internal_static_bit_workflowScheduler_grpc_resource_allocator_gencode_CreateTaskPodRequest_descriptor;
  }

  @SuppressWarnings({"rawtypes"})
  protected com.google.protobuf.MapField internalGetMapField(
      int number) {
    switch (number) {
      case 6:
        return internalGetEnv();
      default:
        throw new RuntimeException(
            "Invalid map field number: " + number);
    }
  }
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return bit.workflowScheduler.grpc.resource_allocator.gencode.ResourceAllocator.internal_static_bit_workflowScheduler_grpc_resource_allocator_gencode_CreateTaskPodRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            bit.workflowScheduler.grpc.resource_allocator.gencode.CreateTaskPodRequest.class, bit.workflowScheduler.grpc.resource_allocator.gencode.CreateTaskPodRequest.Builder.class);
  }

  private int bitField0_;
  public static final int WORKFLOWID_FIELD_NUMBER = 1;
  private volatile java.lang.Object workflowId_;
  /**
   * <pre>
   *workflow的ID
   * </pre>
   *
   * <code>string workflowId = 1;</code>
   */
  public java.lang.String getWorkflowId() {
    java.lang.Object ref = workflowId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      workflowId_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *workflow的ID
   * </pre>
   *
   * <code>string workflowId = 1;</code>
   */
  public com.google.protobuf.ByteString
      getWorkflowIdBytes() {
    java.lang.Object ref = workflowId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      workflowId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TASKNAME_FIELD_NUMBER = 2;
  private volatile java.lang.Object taskName_;
  /**
   * <pre>
   *taskName
   * </pre>
   *
   * <code>string taskName = 2;</code>
   */
  public java.lang.String getTaskName() {
    java.lang.Object ref = taskName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      taskName_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *taskName
   * </pre>
   *
   * <code>string taskName = 2;</code>
   */
  public com.google.protobuf.ByteString
      getTaskNameBytes() {
    java.lang.Object ref = taskName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      taskName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int IMAGE_FIELD_NUMBER = 3;
  private volatile java.lang.Object image_;
  /**
   * <pre>
   *任务镜像
   * </pre>
   *
   * <code>string image = 3;</code>
   */
  public java.lang.String getImage() {
    java.lang.Object ref = image_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      image_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *任务镜像
   * </pre>
   *
   * <code>string image = 3;</code>
   */
  public com.google.protobuf.ByteString
      getImageBytes() {
    java.lang.Object ref = image_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      image_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CPU_FIELD_NUMBER = 4;
  private long cpu_;
  /**
   * <pre>
   *基本单位 millicore(1Core=1000millicore)
   * </pre>
   *
   * <code>int64 cpu = 4;</code>
   */
  public long getCpu() {
    return cpu_;
  }

  public static final int MEM_FIELD_NUMBER = 5;
  private long mem_;
  /**
   * <pre>
   *基本单位 MiB
   * </pre>
   *
   * <code>int64 mem = 5;</code>
   */
  public long getMem() {
    return mem_;
  }

  public static final int ENV_FIELD_NUMBER = 6;
  private static final class EnvDefaultEntryHolder {
    static final com.google.protobuf.MapEntry<
        java.lang.String, java.lang.String> defaultEntry =
            com.google.protobuf.MapEntry
            .<java.lang.String, java.lang.String>newDefaultInstance(
                bit.workflowScheduler.grpc.resource_allocator.gencode.ResourceAllocator.internal_static_bit_workflowScheduler_grpc_resource_allocator_gencode_CreateTaskPodRequest_EnvEntry_descriptor, 
                com.google.protobuf.WireFormat.FieldType.STRING,
                "",
                com.google.protobuf.WireFormat.FieldType.STRING,
                "");
  }
  private com.google.protobuf.MapField<
      java.lang.String, java.lang.String> env_;
  private com.google.protobuf.MapField<java.lang.String, java.lang.String>
  internalGetEnv() {
    if (env_ == null) {
      return com.google.protobuf.MapField.emptyMapField(
          EnvDefaultEntryHolder.defaultEntry);
    }
    return env_;
  }

  public int getEnvCount() {
    return internalGetEnv().getMap().size();
  }
  /**
   * <pre>
   *需要输入给 POD 的环境变量
   * </pre>
   *
   * <code>map&lt;string, string&gt; env = 6;</code>
   */

  public boolean containsEnv(
      java.lang.String key) {
    if (key == null) { throw new java.lang.NullPointerException(); }
    return internalGetEnv().getMap().containsKey(key);
  }
  /**
   * Use {@link #getEnvMap()} instead.
   */
  @java.lang.Deprecated
  public java.util.Map<java.lang.String, java.lang.String> getEnv() {
    return getEnvMap();
  }
  /**
   * <pre>
   *需要输入给 POD 的环境变量
   * </pre>
   *
   * <code>map&lt;string, string&gt; env = 6;</code>
   */

  public java.util.Map<java.lang.String, java.lang.String> getEnvMap() {
    return internalGetEnv().getMap();
  }
  /**
   * <pre>
   *需要输入给 POD 的环境变量
   * </pre>
   *
   * <code>map&lt;string, string&gt; env = 6;</code>
   */

  public java.lang.String getEnvOrDefault(
      java.lang.String key,
      java.lang.String defaultValue) {
    if (key == null) { throw new java.lang.NullPointerException(); }
    java.util.Map<java.lang.String, java.lang.String> map =
        internalGetEnv().getMap();
    return map.containsKey(key) ? map.get(key) : defaultValue;
  }
  /**
   * <pre>
   *需要输入给 POD 的环境变量
   * </pre>
   *
   * <code>map&lt;string, string&gt; env = 6;</code>
   */

  public java.lang.String getEnvOrThrow(
      java.lang.String key) {
    if (key == null) { throw new java.lang.NullPointerException(); }
    java.util.Map<java.lang.String, java.lang.String> map =
        internalGetEnv().getMap();
    if (!map.containsKey(key)) {
      throw new java.lang.IllegalArgumentException();
    }
    return map.get(key);
  }

  public static final int INPUT_VECTOR_FIELD_NUMBER = 7;
  private com.google.protobuf.LazyStringList inputVector_;
  /**
   * <pre>
   * 输入向量
   * </pre>
   *
   * <code>repeated string input_vector = 7;</code>
   */
  public com.google.protobuf.ProtocolStringList
      getInputVectorList() {
    return inputVector_;
  }
  /**
   * <pre>
   * 输入向量
   * </pre>
   *
   * <code>repeated string input_vector = 7;</code>
   */
  public int getInputVectorCount() {
    return inputVector_.size();
  }
  /**
   * <pre>
   * 输入向量
   * </pre>
   *
   * <code>repeated string input_vector = 7;</code>
   */
  public java.lang.String getInputVector(int index) {
    return inputVector_.get(index);
  }
  /**
   * <pre>
   * 输入向量
   * </pre>
   *
   * <code>repeated string input_vector = 7;</code>
   */
  public com.google.protobuf.ByteString
      getInputVectorBytes(int index) {
    return inputVector_.getByteString(index);
  }

  public static final int OUTPUT_VECTOR_FIELD_NUMBER = 8;
  private com.google.protobuf.LazyStringList outputVector_;
  /**
   * <pre>
   * 输出向量
   * </pre>
   *
   * <code>repeated string output_vector = 8;</code>
   */
  public com.google.protobuf.ProtocolStringList
      getOutputVectorList() {
    return outputVector_;
  }
  /**
   * <pre>
   * 输出向量
   * </pre>
   *
   * <code>repeated string output_vector = 8;</code>
   */
  public int getOutputVectorCount() {
    return outputVector_.size();
  }
  /**
   * <pre>
   * 输出向量
   * </pre>
   *
   * <code>repeated string output_vector = 8;</code>
   */
  public java.lang.String getOutputVector(int index) {
    return outputVector_.get(index);
  }
  /**
   * <pre>
   * 输出向量
   * </pre>
   *
   * <code>repeated string output_vector = 8;</code>
   */
  public com.google.protobuf.ByteString
      getOutputVectorBytes(int index) {
    return outputVector_.getByteString(index);
  }

  public static final int CUSTOMIZATION_FIELD_NUMBER = 9;
  private boolean customization_;
  /**
   * <pre>
   *time_grade暂时用不到。若customization=true且cost_grade=false，则pod配置资源最大化，即request=limit；若customization=true且cost_grade=true，则pod配置资源最小化；否则，按之前流程走
   * </pre>
   *
   * <code>bool customization = 9;</code>
   */
  public boolean getCustomization() {
    return customization_;
  }

  public static final int TIME_GRADE_FIELD_NUMBER = 10;
  private boolean timeGrade_;
  /**
   * <pre>
   * 是否存在时间等级
   * </pre>
   *
   * <code>bool time_grade = 10;</code>
   */
  public boolean getTimeGrade() {
    return timeGrade_;
  }

  public static final int COST_GRADE_FIELD_NUMBER = 11;
  private boolean costGrade_;
  /**
   * <pre>
   * 是否花费（资金）等级
   * </pre>
   *
   * <code>bool cost_grade = 11;</code>
   */
  public boolean getCostGrade() {
    return costGrade_;
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getWorkflowIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, workflowId_);
    }
    if (!getTaskNameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, taskName_);
    }
    if (!getImageBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, image_);
    }
    if (cpu_ != 0L) {
      output.writeInt64(4, cpu_);
    }
    if (mem_ != 0L) {
      output.writeInt64(5, mem_);
    }
    com.google.protobuf.GeneratedMessageV3
      .serializeStringMapTo(
        output,
        internalGetEnv(),
        EnvDefaultEntryHolder.defaultEntry,
        6);
    for (int i = 0; i < inputVector_.size(); i++) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 7, inputVector_.getRaw(i));
    }
    for (int i = 0; i < outputVector_.size(); i++) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 8, outputVector_.getRaw(i));
    }
    if (customization_ != false) {
      output.writeBool(9, customization_);
    }
    if (timeGrade_ != false) {
      output.writeBool(10, timeGrade_);
    }
    if (costGrade_ != false) {
      output.writeBool(11, costGrade_);
    }
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getWorkflowIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, workflowId_);
    }
    if (!getTaskNameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, taskName_);
    }
    if (!getImageBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, image_);
    }
    if (cpu_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(4, cpu_);
    }
    if (mem_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(5, mem_);
    }
    for (java.util.Map.Entry<java.lang.String, java.lang.String> entry
         : internalGetEnv().getMap().entrySet()) {
      com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
      env__ = EnvDefaultEntryHolder.defaultEntry.newBuilderForType()
          .setKey(entry.getKey())
          .setValue(entry.getValue())
          .build();
      size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(6, env__);
    }
    {
      int dataSize = 0;
      for (int i = 0; i < inputVector_.size(); i++) {
        dataSize += computeStringSizeNoTag(inputVector_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getInputVectorList().size();
    }
    {
      int dataSize = 0;
      for (int i = 0; i < outputVector_.size(); i++) {
        dataSize += computeStringSizeNoTag(outputVector_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getOutputVectorList().size();
    }
    if (customization_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(9, customization_);
    }
    if (timeGrade_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(10, timeGrade_);
    }
    if (costGrade_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(11, costGrade_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof bit.workflowScheduler.grpc.resource_allocator.gencode.CreateTaskPodRequest)) {
      return super.equals(obj);
    }
    bit.workflowScheduler.grpc.resource_allocator.gencode.CreateTaskPodRequest other = (bit.workflowScheduler.grpc.resource_allocator.gencode.CreateTaskPodRequest) obj;

    boolean result = true;
    result = result && getWorkflowId()
        .equals(other.getWorkflowId());
    result = result && getTaskName()
        .equals(other.getTaskName());
    result = result && getImage()
        .equals(other.getImage());
    result = result && (getCpu()
        == other.getCpu());
    result = result && (getMem()
        == other.getMem());
    result = result && internalGetEnv().equals(
        other.internalGetEnv());
    result = result && getInputVectorList()
        .equals(other.getInputVectorList());
    result = result && getOutputVectorList()
        .equals(other.getOutputVectorList());
    result = result && (getCustomization()
        == other.getCustomization());
    result = result && (getTimeGrade()
        == other.getTimeGrade());
    result = result && (getCostGrade()
        == other.getCostGrade());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + WORKFLOWID_FIELD_NUMBER;
    hash = (53 * hash) + getWorkflowId().hashCode();
    hash = (37 * hash) + TASKNAME_FIELD_NUMBER;
    hash = (53 * hash) + getTaskName().hashCode();
    hash = (37 * hash) + IMAGE_FIELD_NUMBER;
    hash = (53 * hash) + getImage().hashCode();
    hash = (37 * hash) + CPU_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getCpu());
    hash = (37 * hash) + MEM_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getMem());
    if (!internalGetEnv().getMap().isEmpty()) {
      hash = (37 * hash) + ENV_FIELD_NUMBER;
      hash = (53 * hash) + internalGetEnv().hashCode();
    }
    if (getInputVectorCount() > 0) {
      hash = (37 * hash) + INPUT_VECTOR_FIELD_NUMBER;
      hash = (53 * hash) + getInputVectorList().hashCode();
    }
    if (getOutputVectorCount() > 0) {
      hash = (37 * hash) + OUTPUT_VECTOR_FIELD_NUMBER;
      hash = (53 * hash) + getOutputVectorList().hashCode();
    }
    hash = (37 * hash) + CUSTOMIZATION_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getCustomization());
    hash = (37 * hash) + TIME_GRADE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getTimeGrade());
    hash = (37 * hash) + COST_GRADE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getCostGrade());
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static bit.workflowScheduler.grpc.resource_allocator.gencode.CreateTaskPodRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static bit.workflowScheduler.grpc.resource_allocator.gencode.CreateTaskPodRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static bit.workflowScheduler.grpc.resource_allocator.gencode.CreateTaskPodRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static bit.workflowScheduler.grpc.resource_allocator.gencode.CreateTaskPodRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static bit.workflowScheduler.grpc.resource_allocator.gencode.CreateTaskPodRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static bit.workflowScheduler.grpc.resource_allocator.gencode.CreateTaskPodRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static bit.workflowScheduler.grpc.resource_allocator.gencode.CreateTaskPodRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static bit.workflowScheduler.grpc.resource_allocator.gencode.CreateTaskPodRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static bit.workflowScheduler.grpc.resource_allocator.gencode.CreateTaskPodRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static bit.workflowScheduler.grpc.resource_allocator.gencode.CreateTaskPodRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static bit.workflowScheduler.grpc.resource_allocator.gencode.CreateTaskPodRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static bit.workflowScheduler.grpc.resource_allocator.gencode.CreateTaskPodRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(bit.workflowScheduler.grpc.resource_allocator.gencode.CreateTaskPodRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   *请求创建任务POD
   * </pre>
   *
   * Protobuf type {@code bit.workflowScheduler.grpc.resource_allocator.gencode.CreateTaskPodRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:bit.workflowScheduler.grpc.resource_allocator.gencode.CreateTaskPodRequest)
      bit.workflowScheduler.grpc.resource_allocator.gencode.CreateTaskPodRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return bit.workflowScheduler.grpc.resource_allocator.gencode.ResourceAllocator.internal_static_bit_workflowScheduler_grpc_resource_allocator_gencode_CreateTaskPodRequest_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 6:
          return internalGetEnv();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMutableMapField(
        int number) {
      switch (number) {
        case 6:
          return internalGetMutableEnv();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return bit.workflowScheduler.grpc.resource_allocator.gencode.ResourceAllocator.internal_static_bit_workflowScheduler_grpc_resource_allocator_gencode_CreateTaskPodRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              bit.workflowScheduler.grpc.resource_allocator.gencode.CreateTaskPodRequest.class, bit.workflowScheduler.grpc.resource_allocator.gencode.CreateTaskPodRequest.Builder.class);
    }

    // Construct using bit.workflowScheduler.grpc.resource_allocator.gencode.CreateTaskPodRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      workflowId_ = "";

      taskName_ = "";

      image_ = "";

      cpu_ = 0L;

      mem_ = 0L;

      internalGetMutableEnv().clear();
      inputVector_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000040);
      outputVector_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000080);
      customization_ = false;

      timeGrade_ = false;

      costGrade_ = false;

      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return bit.workflowScheduler.grpc.resource_allocator.gencode.ResourceAllocator.internal_static_bit_workflowScheduler_grpc_resource_allocator_gencode_CreateTaskPodRequest_descriptor;
    }

    public bit.workflowScheduler.grpc.resource_allocator.gencode.CreateTaskPodRequest getDefaultInstanceForType() {
      return bit.workflowScheduler.grpc.resource_allocator.gencode.CreateTaskPodRequest.getDefaultInstance();
    }

    public bit.workflowScheduler.grpc.resource_allocator.gencode.CreateTaskPodRequest build() {
      bit.workflowScheduler.grpc.resource_allocator.gencode.CreateTaskPodRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public bit.workflowScheduler.grpc.resource_allocator.gencode.CreateTaskPodRequest buildPartial() {
      bit.workflowScheduler.grpc.resource_allocator.gencode.CreateTaskPodRequest result = new bit.workflowScheduler.grpc.resource_allocator.gencode.CreateTaskPodRequest(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      result.workflowId_ = workflowId_;
      result.taskName_ = taskName_;
      result.image_ = image_;
      result.cpu_ = cpu_;
      result.mem_ = mem_;
      result.env_ = internalGetEnv();
      result.env_.makeImmutable();
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        inputVector_ = inputVector_.getUnmodifiableView();
        bitField0_ = (bitField0_ & ~0x00000040);
      }
      result.inputVector_ = inputVector_;
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        outputVector_ = outputVector_.getUnmodifiableView();
        bitField0_ = (bitField0_ & ~0x00000080);
      }
      result.outputVector_ = outputVector_;
      result.customization_ = customization_;
      result.timeGrade_ = timeGrade_;
      result.costGrade_ = costGrade_;
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof bit.workflowScheduler.grpc.resource_allocator.gencode.CreateTaskPodRequest) {
        return mergeFrom((bit.workflowScheduler.grpc.resource_allocator.gencode.CreateTaskPodRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(bit.workflowScheduler.grpc.resource_allocator.gencode.CreateTaskPodRequest other) {
      if (other == bit.workflowScheduler.grpc.resource_allocator.gencode.CreateTaskPodRequest.getDefaultInstance()) return this;
      if (!other.getWorkflowId().isEmpty()) {
        workflowId_ = other.workflowId_;
        onChanged();
      }
      if (!other.getTaskName().isEmpty()) {
        taskName_ = other.taskName_;
        onChanged();
      }
      if (!other.getImage().isEmpty()) {
        image_ = other.image_;
        onChanged();
      }
      if (other.getCpu() != 0L) {
        setCpu(other.getCpu());
      }
      if (other.getMem() != 0L) {
        setMem(other.getMem());
      }
      internalGetMutableEnv().mergeFrom(
          other.internalGetEnv());
      if (!other.inputVector_.isEmpty()) {
        if (inputVector_.isEmpty()) {
          inputVector_ = other.inputVector_;
          bitField0_ = (bitField0_ & ~0x00000040);
        } else {
          ensureInputVectorIsMutable();
          inputVector_.addAll(other.inputVector_);
        }
        onChanged();
      }
      if (!other.outputVector_.isEmpty()) {
        if (outputVector_.isEmpty()) {
          outputVector_ = other.outputVector_;
          bitField0_ = (bitField0_ & ~0x00000080);
        } else {
          ensureOutputVectorIsMutable();
          outputVector_.addAll(other.outputVector_);
        }
        onChanged();
      }
      if (other.getCustomization() != false) {
        setCustomization(other.getCustomization());
      }
      if (other.getTimeGrade() != false) {
        setTimeGrade(other.getTimeGrade());
      }
      if (other.getCostGrade() != false) {
        setCostGrade(other.getCostGrade());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      bit.workflowScheduler.grpc.resource_allocator.gencode.CreateTaskPodRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (bit.workflowScheduler.grpc.resource_allocator.gencode.CreateTaskPodRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.lang.Object workflowId_ = "";
    /**
     * <pre>
     *workflow的ID
     * </pre>
     *
     * <code>string workflowId = 1;</code>
     */
    public java.lang.String getWorkflowId() {
      java.lang.Object ref = workflowId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        workflowId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     *workflow的ID
     * </pre>
     *
     * <code>string workflowId = 1;</code>
     */
    public com.google.protobuf.ByteString
        getWorkflowIdBytes() {
      java.lang.Object ref = workflowId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        workflowId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *workflow的ID
     * </pre>
     *
     * <code>string workflowId = 1;</code>
     */
    public Builder setWorkflowId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      workflowId_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *workflow的ID
     * </pre>
     *
     * <code>string workflowId = 1;</code>
     */
    public Builder clearWorkflowId() {
      
      workflowId_ = getDefaultInstance().getWorkflowId();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *workflow的ID
     * </pre>
     *
     * <code>string workflowId = 1;</code>
     */
    public Builder setWorkflowIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      workflowId_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object taskName_ = "";
    /**
     * <pre>
     *taskName
     * </pre>
     *
     * <code>string taskName = 2;</code>
     */
    public java.lang.String getTaskName() {
      java.lang.Object ref = taskName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        taskName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     *taskName
     * </pre>
     *
     * <code>string taskName = 2;</code>
     */
    public com.google.protobuf.ByteString
        getTaskNameBytes() {
      java.lang.Object ref = taskName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        taskName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *taskName
     * </pre>
     *
     * <code>string taskName = 2;</code>
     */
    public Builder setTaskName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      taskName_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *taskName
     * </pre>
     *
     * <code>string taskName = 2;</code>
     */
    public Builder clearTaskName() {
      
      taskName_ = getDefaultInstance().getTaskName();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *taskName
     * </pre>
     *
     * <code>string taskName = 2;</code>
     */
    public Builder setTaskNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      taskName_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object image_ = "";
    /**
     * <pre>
     *任务镜像
     * </pre>
     *
     * <code>string image = 3;</code>
     */
    public java.lang.String getImage() {
      java.lang.Object ref = image_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        image_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     *任务镜像
     * </pre>
     *
     * <code>string image = 3;</code>
     */
    public com.google.protobuf.ByteString
        getImageBytes() {
      java.lang.Object ref = image_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        image_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *任务镜像
     * </pre>
     *
     * <code>string image = 3;</code>
     */
    public Builder setImage(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      image_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *任务镜像
     * </pre>
     *
     * <code>string image = 3;</code>
     */
    public Builder clearImage() {
      
      image_ = getDefaultInstance().getImage();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *任务镜像
     * </pre>
     *
     * <code>string image = 3;</code>
     */
    public Builder setImageBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      image_ = value;
      onChanged();
      return this;
    }

    private long cpu_ ;
    /**
     * <pre>
     *基本单位 millicore(1Core=1000millicore)
     * </pre>
     *
     * <code>int64 cpu = 4;</code>
     */
    public long getCpu() {
      return cpu_;
    }
    /**
     * <pre>
     *基本单位 millicore(1Core=1000millicore)
     * </pre>
     *
     * <code>int64 cpu = 4;</code>
     */
    public Builder setCpu(long value) {
      
      cpu_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *基本单位 millicore(1Core=1000millicore)
     * </pre>
     *
     * <code>int64 cpu = 4;</code>
     */
    public Builder clearCpu() {
      
      cpu_ = 0L;
      onChanged();
      return this;
    }

    private long mem_ ;
    /**
     * <pre>
     *基本单位 MiB
     * </pre>
     *
     * <code>int64 mem = 5;</code>
     */
    public long getMem() {
      return mem_;
    }
    /**
     * <pre>
     *基本单位 MiB
     * </pre>
     *
     * <code>int64 mem = 5;</code>
     */
    public Builder setMem(long value) {
      
      mem_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *基本单位 MiB
     * </pre>
     *
     * <code>int64 mem = 5;</code>
     */
    public Builder clearMem() {
      
      mem_ = 0L;
      onChanged();
      return this;
    }

    private com.google.protobuf.MapField<
        java.lang.String, java.lang.String> env_;
    private com.google.protobuf.MapField<java.lang.String, java.lang.String>
    internalGetEnv() {
      if (env_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            EnvDefaultEntryHolder.defaultEntry);
      }
      return env_;
    }
    private com.google.protobuf.MapField<java.lang.String, java.lang.String>
    internalGetMutableEnv() {
      onChanged();;
      if (env_ == null) {
        env_ = com.google.protobuf.MapField.newMapField(
            EnvDefaultEntryHolder.defaultEntry);
      }
      if (!env_.isMutable()) {
        env_ = env_.copy();
      }
      return env_;
    }

    public int getEnvCount() {
      return internalGetEnv().getMap().size();
    }
    /**
     * <pre>
     *需要输入给 POD 的环境变量
     * </pre>
     *
     * <code>map&lt;string, string&gt; env = 6;</code>
     */

    public boolean containsEnv(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      return internalGetEnv().getMap().containsKey(key);
    }
    /**
     * Use {@link #getEnvMap()} instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.String> getEnv() {
      return getEnvMap();
    }
    /**
     * <pre>
     *需要输入给 POD 的环境变量
     * </pre>
     *
     * <code>map&lt;string, string&gt; env = 6;</code>
     */

    public java.util.Map<java.lang.String, java.lang.String> getEnvMap() {
      return internalGetEnv().getMap();
    }
    /**
     * <pre>
     *需要输入给 POD 的环境变量
     * </pre>
     *
     * <code>map&lt;string, string&gt; env = 6;</code>
     */

    public java.lang.String getEnvOrDefault(
        java.lang.String key,
        java.lang.String defaultValue) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetEnv().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <pre>
     *需要输入给 POD 的环境变量
     * </pre>
     *
     * <code>map&lt;string, string&gt; env = 6;</code>
     */

    public java.lang.String getEnvOrThrow(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetEnv().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }

    public Builder clearEnv() {
      internalGetMutableEnv().getMutableMap()
          .clear();
      return this;
    }
    /**
     * <pre>
     *需要输入给 POD 的环境变量
     * </pre>
     *
     * <code>map&lt;string, string&gt; env = 6;</code>
     */

    public Builder removeEnv(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      internalGetMutableEnv().getMutableMap()
          .remove(key);
      return this;
    }
    /**
     * Use alternate mutation accessors instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.String>
    getMutableEnv() {
      return internalGetMutableEnv().getMutableMap();
    }
    /**
     * <pre>
     *需要输入给 POD 的环境变量
     * </pre>
     *
     * <code>map&lt;string, string&gt; env = 6;</code>
     */
    public Builder putEnv(
        java.lang.String key,
        java.lang.String value) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      if (value == null) { throw new java.lang.NullPointerException(); }
      internalGetMutableEnv().getMutableMap()
          .put(key, value);
      return this;
    }
    /**
     * <pre>
     *需要输入给 POD 的环境变量
     * </pre>
     *
     * <code>map&lt;string, string&gt; env = 6;</code>
     */

    public Builder putAllEnv(
        java.util.Map<java.lang.String, java.lang.String> values) {
      internalGetMutableEnv().getMutableMap()
          .putAll(values);
      return this;
    }

    private com.google.protobuf.LazyStringList inputVector_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    private void ensureInputVectorIsMutable() {
      if (!((bitField0_ & 0x00000040) == 0x00000040)) {
        inputVector_ = new com.google.protobuf.LazyStringArrayList(inputVector_);
        bitField0_ |= 0x00000040;
       }
    }
    /**
     * <pre>
     * 输入向量
     * </pre>
     *
     * <code>repeated string input_vector = 7;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getInputVectorList() {
      return inputVector_.getUnmodifiableView();
    }
    /**
     * <pre>
     * 输入向量
     * </pre>
     *
     * <code>repeated string input_vector = 7;</code>
     */
    public int getInputVectorCount() {
      return inputVector_.size();
    }
    /**
     * <pre>
     * 输入向量
     * </pre>
     *
     * <code>repeated string input_vector = 7;</code>
     */
    public java.lang.String getInputVector(int index) {
      return inputVector_.get(index);
    }
    /**
     * <pre>
     * 输入向量
     * </pre>
     *
     * <code>repeated string input_vector = 7;</code>
     */
    public com.google.protobuf.ByteString
        getInputVectorBytes(int index) {
      return inputVector_.getByteString(index);
    }
    /**
     * <pre>
     * 输入向量
     * </pre>
     *
     * <code>repeated string input_vector = 7;</code>
     */
    public Builder setInputVector(
        int index, java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureInputVectorIsMutable();
      inputVector_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 输入向量
     * </pre>
     *
     * <code>repeated string input_vector = 7;</code>
     */
    public Builder addInputVector(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureInputVectorIsMutable();
      inputVector_.add(value);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 输入向量
     * </pre>
     *
     * <code>repeated string input_vector = 7;</code>
     */
    public Builder addAllInputVector(
        java.lang.Iterable<java.lang.String> values) {
      ensureInputVectorIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, inputVector_);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 输入向量
     * </pre>
     *
     * <code>repeated string input_vector = 7;</code>
     */
    public Builder clearInputVector() {
      inputVector_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000040);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 输入向量
     * </pre>
     *
     * <code>repeated string input_vector = 7;</code>
     */
    public Builder addInputVectorBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      ensureInputVectorIsMutable();
      inputVector_.add(value);
      onChanged();
      return this;
    }

    private com.google.protobuf.LazyStringList outputVector_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    private void ensureOutputVectorIsMutable() {
      if (!((bitField0_ & 0x00000080) == 0x00000080)) {
        outputVector_ = new com.google.protobuf.LazyStringArrayList(outputVector_);
        bitField0_ |= 0x00000080;
       }
    }
    /**
     * <pre>
     * 输出向量
     * </pre>
     *
     * <code>repeated string output_vector = 8;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getOutputVectorList() {
      return outputVector_.getUnmodifiableView();
    }
    /**
     * <pre>
     * 输出向量
     * </pre>
     *
     * <code>repeated string output_vector = 8;</code>
     */
    public int getOutputVectorCount() {
      return outputVector_.size();
    }
    /**
     * <pre>
     * 输出向量
     * </pre>
     *
     * <code>repeated string output_vector = 8;</code>
     */
    public java.lang.String getOutputVector(int index) {
      return outputVector_.get(index);
    }
    /**
     * <pre>
     * 输出向量
     * </pre>
     *
     * <code>repeated string output_vector = 8;</code>
     */
    public com.google.protobuf.ByteString
        getOutputVectorBytes(int index) {
      return outputVector_.getByteString(index);
    }
    /**
     * <pre>
     * 输出向量
     * </pre>
     *
     * <code>repeated string output_vector = 8;</code>
     */
    public Builder setOutputVector(
        int index, java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureOutputVectorIsMutable();
      outputVector_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 输出向量
     * </pre>
     *
     * <code>repeated string output_vector = 8;</code>
     */
    public Builder addOutputVector(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureOutputVectorIsMutable();
      outputVector_.add(value);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 输出向量
     * </pre>
     *
     * <code>repeated string output_vector = 8;</code>
     */
    public Builder addAllOutputVector(
        java.lang.Iterable<java.lang.String> values) {
      ensureOutputVectorIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, outputVector_);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 输出向量
     * </pre>
     *
     * <code>repeated string output_vector = 8;</code>
     */
    public Builder clearOutputVector() {
      outputVector_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000080);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 输出向量
     * </pre>
     *
     * <code>repeated string output_vector = 8;</code>
     */
    public Builder addOutputVectorBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      ensureOutputVectorIsMutable();
      outputVector_.add(value);
      onChanged();
      return this;
    }

    private boolean customization_ ;
    /**
     * <pre>
     *time_grade暂时用不到。若customization=true且cost_grade=false，则pod配置资源最大化，即request=limit；若customization=true且cost_grade=true，则pod配置资源最小化；否则，按之前流程走
     * </pre>
     *
     * <code>bool customization = 9;</code>
     */
    public boolean getCustomization() {
      return customization_;
    }
    /**
     * <pre>
     *time_grade暂时用不到。若customization=true且cost_grade=false，则pod配置资源最大化，即request=limit；若customization=true且cost_grade=true，则pod配置资源最小化；否则，按之前流程走
     * </pre>
     *
     * <code>bool customization = 9;</code>
     */
    public Builder setCustomization(boolean value) {
      
      customization_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *time_grade暂时用不到。若customization=true且cost_grade=false，则pod配置资源最大化，即request=limit；若customization=true且cost_grade=true，则pod配置资源最小化；否则，按之前流程走
     * </pre>
     *
     * <code>bool customization = 9;</code>
     */
    public Builder clearCustomization() {
      
      customization_ = false;
      onChanged();
      return this;
    }

    private boolean timeGrade_ ;
    /**
     * <pre>
     * 是否存在时间等级
     * </pre>
     *
     * <code>bool time_grade = 10;</code>
     */
    public boolean getTimeGrade() {
      return timeGrade_;
    }
    /**
     * <pre>
     * 是否存在时间等级
     * </pre>
     *
     * <code>bool time_grade = 10;</code>
     */
    public Builder setTimeGrade(boolean value) {
      
      timeGrade_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 是否存在时间等级
     * </pre>
     *
     * <code>bool time_grade = 10;</code>
     */
    public Builder clearTimeGrade() {
      
      timeGrade_ = false;
      onChanged();
      return this;
    }

    private boolean costGrade_ ;
    /**
     * <pre>
     * 是否花费（资金）等级
     * </pre>
     *
     * <code>bool cost_grade = 11;</code>
     */
    public boolean getCostGrade() {
      return costGrade_;
    }
    /**
     * <pre>
     * 是否花费（资金）等级
     * </pre>
     *
     * <code>bool cost_grade = 11;</code>
     */
    public Builder setCostGrade(boolean value) {
      
      costGrade_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 是否花费（资金）等级
     * </pre>
     *
     * <code>bool cost_grade = 11;</code>
     */
    public Builder clearCostGrade() {
      
      costGrade_ = false;
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:bit.workflowScheduler.grpc.resource_allocator.gencode.CreateTaskPodRequest)
  }

  // @@protoc_insertion_point(class_scope:bit.workflowScheduler.grpc.resource_allocator.gencode.CreateTaskPodRequest)
  private static final bit.workflowScheduler.grpc.resource_allocator.gencode.CreateTaskPodRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new bit.workflowScheduler.grpc.resource_allocator.gencode.CreateTaskPodRequest();
  }

  public static bit.workflowScheduler.grpc.resource_allocator.gencode.CreateTaskPodRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<CreateTaskPodRequest>
      PARSER = new com.google.protobuf.AbstractParser<CreateTaskPodRequest>() {
    public CreateTaskPodRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new CreateTaskPodRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<CreateTaskPodRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<CreateTaskPodRequest> getParserForType() {
    return PARSER;
  }

  public bit.workflowScheduler.grpc.resource_allocator.gencode.CreateTaskPodRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

