// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: resource_allocator.proto

package bit.workflowScheduler.grpc.resource_allocator.gencode;

public interface CreateSchedulerPodRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:bit.workflowScheduler.grpc.resource_allocator.gencode.CreateSchedulerPodRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *镜像
   * </pre>
   *
   * <code>string image = 1;</code>
   */
  java.lang.String getImage();
  /**
   * <pre>
   *镜像
   * </pre>
   *
   * <code>string image = 1;</code>
   */
  com.google.protobuf.ByteString
      getImageBytes();

  /**
   * <pre>
   *基本单位 millicore(1Core=1000millicore)
   * </pre>
   *
   * <code>int64 cpu = 2;</code>
   */
  long getCpu();

  /**
   * <pre>
   *基本单位 MiB
   * </pre>
   *
   * <code>int64 mem = 3;</code>
   */
  long getMem();

  /**
   * <pre>
   *需要输入给 POD 的环境变量
   * </pre>
   *
   * <code>repeated string env = 4;</code>
   */
  java.util.List<java.lang.String>
      getEnvList();
  /**
   * <pre>
   *需要输入给 POD 的环境变量
   * </pre>
   *
   * <code>repeated string env = 4;</code>
   */
  int getEnvCount();
  /**
   * <pre>
   *需要输入给 POD 的环境变量
   * </pre>
   *
   * <code>repeated string env = 4;</code>
   */
  java.lang.String getEnv(int index);
  /**
   * <pre>
   *需要输入给 POD 的环境变量
   * </pre>
   *
   * <code>repeated string env = 4;</code>
   */
  com.google.protobuf.ByteString
      getEnvBytes(int index);
}
