// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: resource_allocator.proto

package bit.workflowScheduler.grpc.resource_allocator.gencode;

public interface CreateTaskPodResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:bit.workflowScheduler.grpc.resource_allocator.gencode.CreateTaskPodResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *成功创建 pod 的状态码（成功&gt;=1，失败置为0）
   * </pre>
   *
   * <code>int32 result = 1;</code>
   */
  int getResult();

  /**
   * <pre>
   *pod共享存储路径
   * </pre>
   *
   * <code>string volumePath = 2;</code>
   */
  java.lang.String getVolumePath();
  /**
   * <pre>
   *pod共享存储路径
   * </pre>
   *
   * <code>string volumePath = 2;</code>
   */
  com.google.protobuf.ByteString
      getVolumePathBytes();

  /**
   * <pre>
   *在失败状态下，可以设置状态码
   *成功状态（result&gt;=1），客户端不关系此字段，置为 0 即可
   * </pre>
   *
   * <code>int32 err_no = 3;</code>
   */
  int getErrNo();
}
