// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: resource_allocator.proto

package bit.workflowScheduler.grpc.resource_allocator.gencode;

public interface DeleteWorkflowNamespaceResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:bit.workflowScheduler.grpc.resource_allocator.gencode.DeleteWorkflowNamespaceResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *资源分配器删除该工作流的namespace的状态码（成功&gt;=1，失败置为0）
   * </pre>
   *
   * <code>int32 result = 1;</code>
   */
  int getResult();
}
