// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: resource_allocator.proto

package bit.workflowScheduler.grpc.resource_allocator.gencode;

public interface GetSchedulerNumResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:bit.workflowScheduler.grpc.resource_allocator.gencode.GetSchedulerNumResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 schedulerPodNum = 1;</code>
   */
  long getSchedulerPodNum();
}
