// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: resource_allocator.proto

package bit.workflowScheduler.grpc.resource_allocator.gencode;

public interface GetSchedulerNumRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:bit.workflowScheduler.grpc.resource_allocator.gencode.GetSchedulerNumRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *调度器的资源request
   * </pre>
   *
   * <code>int64 cpu = 1;</code>
   */
  long getCpu();

  /**
   * <code>int64 mem = 2;</code>
   */
  long getMem();
}
