// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: resource_allocator.proto

package bit.workflowScheduler.grpc.resource_allocator.gencode;

public interface ResourceAllocateInfoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:bit.workflowScheduler.grpc.resource_allocator.gencode.ResourceAllocateInfo)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string schedulerId = 1;</code>
   */
  java.lang.String getSchedulerId();
  /**
   * <code>string schedulerId = 1;</code>
   */
  com.google.protobuf.ByteString
      getSchedulerIdBytes();

  /**
   * <code>.bit.workflowScheduler.grpc.resource_allocator.gencode.ResourceAllocateInfo.resourceDemand currentRequest = 2;</code>
   */
  boolean hasCurrentRequest();
  /**
   * <code>.bit.workflowScheduler.grpc.resource_allocator.gencode.ResourceAllocateInfo.resourceDemand currentRequest = 2;</code>
   */
  bit.workflowScheduler.grpc.resource_allocator.gencode.ResourceAllocateInfo.resourceDemand getCurrentRequest();
  /**
   * <code>.bit.workflowScheduler.grpc.resource_allocator.gencode.ResourceAllocateInfo.resourceDemand currentRequest = 2;</code>
   */
  bit.workflowScheduler.grpc.resource_allocator.gencode.ResourceAllocateInfo.resourceDemandOrBuilder getCurrentRequestOrBuilder();

  /**
   * <code>bool currentRequestStatus = 3;</code>
   */
  boolean getCurrentRequestStatus();
}
