// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: resource_allocator.proto

package bit.workflowScheduler.grpc.resource_allocator.gencode;

/**
 * <pre>
 *资源请求参数
 * </pre>
 *
 * Protobuf type {@code bit.workflowScheduler.grpc.resource_allocator.gencode.ResourceRequest}
 */
public  final class ResourceRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:bit.workflowScheduler.grpc.resource_allocator.gencode.ResourceRequest)
    ResourceRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ResourceRequest.newBuilder() to construct.
  private ResourceRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ResourceRequest() {
    schedulerId_ = "";
    timeStamp_ = 0L;
    customization_ = false;
    timeGrade_ = false;
    costGrade_ = false;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private ResourceRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            schedulerId_ = s;
            break;
          }
          case 16: {

            timeStamp_ = input.readInt64();
            break;
          }
          case 26: {
            bit.workflowScheduler.grpc.resource_allocator.gencode.ResourceRequest.resourceDemand.Builder subBuilder = null;
            if (currentRequest_ != null) {
              subBuilder = currentRequest_.toBuilder();
            }
            currentRequest_ = input.readMessage(bit.workflowScheduler.grpc.resource_allocator.gencode.ResourceRequest.resourceDemand.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(currentRequest_);
              currentRequest_ = subBuilder.buildPartial();
            }

            break;
          }
          case 34: {
            bit.workflowScheduler.grpc.resource_allocator.gencode.ResourceRequest.resourceDemand.Builder subBuilder = null;
            if (nextRequest_ != null) {
              subBuilder = nextRequest_.toBuilder();
            }
            nextRequest_ = input.readMessage(bit.workflowScheduler.grpc.resource_allocator.gencode.ResourceRequest.resourceDemand.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(nextRequest_);
              nextRequest_ = subBuilder.buildPartial();
            }

            break;
          }
          case 42: {
            bit.workflowScheduler.grpc.resource_allocator.gencode.ResourceRequest.resourceDemand.Builder subBuilder = null;
            if (allTasksRequest_ != null) {
              subBuilder = allTasksRequest_.toBuilder();
            }
            allTasksRequest_ = input.readMessage(bit.workflowScheduler.grpc.resource_allocator.gencode.ResourceRequest.resourceDemand.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(allTasksRequest_);
              allTasksRequest_ = subBuilder.buildPartial();
            }

            break;
          }
          case 48: {

            customization_ = input.readBool();
            break;
          }
          case 56: {

            timeGrade_ = input.readBool();
            break;
          }
          case 64: {

            costGrade_ = input.readBool();
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return bit.workflowScheduler.grpc.resource_allocator.gencode.ResourceAllocator.internal_static_bit_workflowScheduler_grpc_resource_allocator_gencode_ResourceRequest_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return bit.workflowScheduler.grpc.resource_allocator.gencode.ResourceAllocator.internal_static_bit_workflowScheduler_grpc_resource_allocator_gencode_ResourceRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            bit.workflowScheduler.grpc.resource_allocator.gencode.ResourceRequest.class, bit.workflowScheduler.grpc.resource_allocator.gencode.ResourceRequest.Builder.class);
  }

  public interface resourceDemandOrBuilder extends
      // @@protoc_insertion_point(interface_extends:bit.workflowScheduler.grpc.resource_allocator.gencode.ResourceRequest.resourceDemand)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *基本单位millicore(1Core=1000millicore) [default = 50]
     * </pre>
     *
     * <code>int64 cpu = 1;</code>
     */
    long getCpu();

    /**
     * <pre>
     *基本单位Mi,1024*1024byte[default = 50]
     * </pre>
     *
     * <code>int64 mem = 2;</code>
     */
    long getMem();
  }
  /**
   * Protobuf type {@code bit.workflowScheduler.grpc.resource_allocator.gencode.ResourceRequest.resourceDemand}
   */
  public  static final class resourceDemand extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:bit.workflowScheduler.grpc.resource_allocator.gencode.ResourceRequest.resourceDemand)
      resourceDemandOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use resourceDemand.newBuilder() to construct.
    private resourceDemand(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private resourceDemand() {
      cpu_ = 0L;
      mem_ = 0L;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private resourceDemand(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              cpu_ = input.readInt64();
              break;
            }
            case 16: {

              mem_ = input.readInt64();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return bit.workflowScheduler.grpc.resource_allocator.gencode.ResourceAllocator.internal_static_bit_workflowScheduler_grpc_resource_allocator_gencode_ResourceRequest_resourceDemand_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return bit.workflowScheduler.grpc.resource_allocator.gencode.ResourceAllocator.internal_static_bit_workflowScheduler_grpc_resource_allocator_gencode_ResourceRequest_resourceDemand_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              bit.workflowScheduler.grpc.resource_allocator.gencode.ResourceRequest.resourceDemand.class, bit.workflowScheduler.grpc.resource_allocator.gencode.ResourceRequest.resourceDemand.Builder.class);
    }

    public static final int CPU_FIELD_NUMBER = 1;
    private long cpu_;
    /**
     * <pre>
     *基本单位millicore(1Core=1000millicore) [default = 50]
     * </pre>
     *
     * <code>int64 cpu = 1;</code>
     */
    public long getCpu() {
      return cpu_;
    }

    public static final int MEM_FIELD_NUMBER = 2;
    private long mem_;
    /**
     * <pre>
     *基本单位Mi,1024*1024byte[default = 50]
     * </pre>
     *
     * <code>int64 mem = 2;</code>
     */
    public long getMem() {
      return mem_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (cpu_ != 0L) {
        output.writeInt64(1, cpu_);
      }
      if (mem_ != 0L) {
        output.writeInt64(2, mem_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (cpu_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, cpu_);
      }
      if (mem_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, mem_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof bit.workflowScheduler.grpc.resource_allocator.gencode.ResourceRequest.resourceDemand)) {
        return super.equals(obj);
      }
      bit.workflowScheduler.grpc.resource_allocator.gencode.ResourceRequest.resourceDemand other = (bit.workflowScheduler.grpc.resource_allocator.gencode.ResourceRequest.resourceDemand) obj;

      boolean result = true;
      result = result && (getCpu()
          == other.getCpu());
      result = result && (getMem()
          == other.getMem());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + CPU_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getCpu());
      hash = (37 * hash) + MEM_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getMem());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static bit.workflowScheduler.grpc.resource_allocator.gencode.ResourceRequest.resourceDemand parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static bit.workflowScheduler.grpc.resource_allocator.gencode.ResourceRequest.resourceDemand parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static bit.workflowScheduler.grpc.resource_allocator.gencode.ResourceRequest.resourceDemand parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static bit.workflowScheduler.grpc.resource_allocator.gencode.ResourceRequest.resourceDemand parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static bit.workflowScheduler.grpc.resource_allocator.gencode.ResourceRequest.resourceDemand parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static bit.workflowScheduler.grpc.resource_allocator.gencode.ResourceRequest.resourceDemand parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static bit.workflowScheduler.grpc.resource_allocator.gencode.ResourceRequest.resourceDemand parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static bit.workflowScheduler.grpc.resource_allocator.gencode.ResourceRequest.resourceDemand parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static bit.workflowScheduler.grpc.resource_allocator.gencode.ResourceRequest.resourceDemand parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static bit.workflowScheduler.grpc.resource_allocator.gencode.ResourceRequest.resourceDemand parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static bit.workflowScheduler.grpc.resource_allocator.gencode.ResourceRequest.resourceDemand parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static bit.workflowScheduler.grpc.resource_allocator.gencode.ResourceRequest.resourceDemand parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(bit.workflowScheduler.grpc.resource_allocator.gencode.ResourceRequest.resourceDemand prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code bit.workflowScheduler.grpc.resource_allocator.gencode.ResourceRequest.resourceDemand}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:bit.workflowScheduler.grpc.resource_allocator.gencode.ResourceRequest.resourceDemand)
        bit.workflowScheduler.grpc.resource_allocator.gencode.ResourceRequest.resourceDemandOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return bit.workflowScheduler.grpc.resource_allocator.gencode.ResourceAllocator.internal_static_bit_workflowScheduler_grpc_resource_allocator_gencode_ResourceRequest_resourceDemand_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return bit.workflowScheduler.grpc.resource_allocator.gencode.ResourceAllocator.internal_static_bit_workflowScheduler_grpc_resource_allocator_gencode_ResourceRequest_resourceDemand_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                bit.workflowScheduler.grpc.resource_allocator.gencode.ResourceRequest.resourceDemand.class, bit.workflowScheduler.grpc.resource_allocator.gencode.ResourceRequest.resourceDemand.Builder.class);
      }

      // Construct using bit.workflowScheduler.grpc.resource_allocator.gencode.ResourceRequest.resourceDemand.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        cpu_ = 0L;

        mem_ = 0L;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return bit.workflowScheduler.grpc.resource_allocator.gencode.ResourceAllocator.internal_static_bit_workflowScheduler_grpc_resource_allocator_gencode_ResourceRequest_resourceDemand_descriptor;
      }

      public bit.workflowScheduler.grpc.resource_allocator.gencode.ResourceRequest.resourceDemand getDefaultInstanceForType() {
        return bit.workflowScheduler.grpc.resource_allocator.gencode.ResourceRequest.resourceDemand.getDefaultInstance();
      }

      public bit.workflowScheduler.grpc.resource_allocator.gencode.ResourceRequest.resourceDemand build() {
        bit.workflowScheduler.grpc.resource_allocator.gencode.ResourceRequest.resourceDemand result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public bit.workflowScheduler.grpc.resource_allocator.gencode.ResourceRequest.resourceDemand buildPartial() {
        bit.workflowScheduler.grpc.resource_allocator.gencode.ResourceRequest.resourceDemand result = new bit.workflowScheduler.grpc.resource_allocator.gencode.ResourceRequest.resourceDemand(this);
        result.cpu_ = cpu_;
        result.mem_ = mem_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof bit.workflowScheduler.grpc.resource_allocator.gencode.ResourceRequest.resourceDemand) {
          return mergeFrom((bit.workflowScheduler.grpc.resource_allocator.gencode.ResourceRequest.resourceDemand)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(bit.workflowScheduler.grpc.resource_allocator.gencode.ResourceRequest.resourceDemand other) {
        if (other == bit.workflowScheduler.grpc.resource_allocator.gencode.ResourceRequest.resourceDemand.getDefaultInstance()) return this;
        if (other.getCpu() != 0L) {
          setCpu(other.getCpu());
        }
        if (other.getMem() != 0L) {
          setMem(other.getMem());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        bit.workflowScheduler.grpc.resource_allocator.gencode.ResourceRequest.resourceDemand parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (bit.workflowScheduler.grpc.resource_allocator.gencode.ResourceRequest.resourceDemand) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private long cpu_ ;
      /**
       * <pre>
       *基本单位millicore(1Core=1000millicore) [default = 50]
       * </pre>
       *
       * <code>int64 cpu = 1;</code>
       */
      public long getCpu() {
        return cpu_;
      }
      /**
       * <pre>
       *基本单位millicore(1Core=1000millicore) [default = 50]
       * </pre>
       *
       * <code>int64 cpu = 1;</code>
       */
      public Builder setCpu(long value) {
        
        cpu_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *基本单位millicore(1Core=1000millicore) [default = 50]
       * </pre>
       *
       * <code>int64 cpu = 1;</code>
       */
      public Builder clearCpu() {
        
        cpu_ = 0L;
        onChanged();
        return this;
      }

      private long mem_ ;
      /**
       * <pre>
       *基本单位Mi,1024*1024byte[default = 50]
       * </pre>
       *
       * <code>int64 mem = 2;</code>
       */
      public long getMem() {
        return mem_;
      }
      /**
       * <pre>
       *基本单位Mi,1024*1024byte[default = 50]
       * </pre>
       *
       * <code>int64 mem = 2;</code>
       */
      public Builder setMem(long value) {
        
        mem_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *基本单位Mi,1024*1024byte[default = 50]
       * </pre>
       *
       * <code>int64 mem = 2;</code>
       */
      public Builder clearMem() {
        
        mem_ = 0L;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:bit.workflowScheduler.grpc.resource_allocator.gencode.ResourceRequest.resourceDemand)
    }

    // @@protoc_insertion_point(class_scope:bit.workflowScheduler.grpc.resource_allocator.gencode.ResourceRequest.resourceDemand)
    private static final bit.workflowScheduler.grpc.resource_allocator.gencode.ResourceRequest.resourceDemand DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new bit.workflowScheduler.grpc.resource_allocator.gencode.ResourceRequest.resourceDemand();
    }

    public static bit.workflowScheduler.grpc.resource_allocator.gencode.ResourceRequest.resourceDemand getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<resourceDemand>
        PARSER = new com.google.protobuf.AbstractParser<resourceDemand>() {
      public resourceDemand parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new resourceDemand(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<resourceDemand> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<resourceDemand> getParserForType() {
      return PARSER;
    }

    public bit.workflowScheduler.grpc.resource_allocator.gencode.ResourceRequest.resourceDemand getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public static final int SCHEDULERID_FIELD_NUMBER = 1;
  private volatile java.lang.Object schedulerId_;
  /**
   * <pre>
   *调度器id
   * </pre>
   *
   * <code>string schedulerId = 1;</code>
   */
  public java.lang.String getSchedulerId() {
    java.lang.Object ref = schedulerId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      schedulerId_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *调度器id
   * </pre>
   *
   * <code>string schedulerId = 1;</code>
   */
  public com.google.protobuf.ByteString
      getSchedulerIdBytes() {
    java.lang.Object ref = schedulerId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      schedulerId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TIMESTAMP_FIELD_NUMBER = 2;
  private long timeStamp_;
  /**
   * <pre>
   *时间戳
   * </pre>
   *
   * <code>int64 timeStamp = 2;</code>
   */
  public long getTimeStamp() {
    return timeStamp_;
  }

  public static final int CURRENTREQUEST_FIELD_NUMBER = 3;
  private bit.workflowScheduler.grpc.resource_allocator.gencode.ResourceRequest.resourceDemand currentRequest_;
  /**
   * <pre>
   *该调度器当前批次ready_tasks资源请求量
   * </pre>
   *
   * <code>.bit.workflowScheduler.grpc.resource_allocator.gencode.ResourceRequest.resourceDemand currentRequest = 3;</code>
   */
  public boolean hasCurrentRequest() {
    return currentRequest_ != null;
  }
  /**
   * <pre>
   *该调度器当前批次ready_tasks资源请求量
   * </pre>
   *
   * <code>.bit.workflowScheduler.grpc.resource_allocator.gencode.ResourceRequest.resourceDemand currentRequest = 3;</code>
   */
  public bit.workflowScheduler.grpc.resource_allocator.gencode.ResourceRequest.resourceDemand getCurrentRequest() {
    return currentRequest_ == null ? bit.workflowScheduler.grpc.resource_allocator.gencode.ResourceRequest.resourceDemand.getDefaultInstance() : currentRequest_;
  }
  /**
   * <pre>
   *该调度器当前批次ready_tasks资源请求量
   * </pre>
   *
   * <code>.bit.workflowScheduler.grpc.resource_allocator.gencode.ResourceRequest.resourceDemand currentRequest = 3;</code>
   */
  public bit.workflowScheduler.grpc.resource_allocator.gencode.ResourceRequest.resourceDemandOrBuilder getCurrentRequestOrBuilder() {
    return getCurrentRequest();
  }

  public static final int NEXTREQUEST_FIELD_NUMBER = 4;
  private bit.workflowScheduler.grpc.resource_allocator.gencode.ResourceRequest.resourceDemand nextRequest_;
  /**
   * <pre>
   *该调度器下一批次ready_tasks资源请求量
   * </pre>
   *
   * <code>.bit.workflowScheduler.grpc.resource_allocator.gencode.ResourceRequest.resourceDemand nextRequest = 4;</code>
   */
  public boolean hasNextRequest() {
    return nextRequest_ != null;
  }
  /**
   * <pre>
   *该调度器下一批次ready_tasks资源请求量
   * </pre>
   *
   * <code>.bit.workflowScheduler.grpc.resource_allocator.gencode.ResourceRequest.resourceDemand nextRequest = 4;</code>
   */
  public bit.workflowScheduler.grpc.resource_allocator.gencode.ResourceRequest.resourceDemand getNextRequest() {
    return nextRequest_ == null ? bit.workflowScheduler.grpc.resource_allocator.gencode.ResourceRequest.resourceDemand.getDefaultInstance() : nextRequest_;
  }
  /**
   * <pre>
   *该调度器下一批次ready_tasks资源请求量
   * </pre>
   *
   * <code>.bit.workflowScheduler.grpc.resource_allocator.gencode.ResourceRequest.resourceDemand nextRequest = 4;</code>
   */
  public bit.workflowScheduler.grpc.resource_allocator.gencode.ResourceRequest.resourceDemandOrBuilder getNextRequestOrBuilder() {
    return getNextRequest();
  }

  public static final int ALLTASKSREQUEST_FIELD_NUMBER = 5;
  private bit.workflowScheduler.grpc.resource_allocator.gencode.ResourceRequest.resourceDemand allTasksRequest_;
  /**
   * <pre>
   *当前该调度器所有待分配任务资源请求总量
   * </pre>
   *
   * <code>.bit.workflowScheduler.grpc.resource_allocator.gencode.ResourceRequest.resourceDemand allTasksRequest = 5;</code>
   */
  public boolean hasAllTasksRequest() {
    return allTasksRequest_ != null;
  }
  /**
   * <pre>
   *当前该调度器所有待分配任务资源请求总量
   * </pre>
   *
   * <code>.bit.workflowScheduler.grpc.resource_allocator.gencode.ResourceRequest.resourceDemand allTasksRequest = 5;</code>
   */
  public bit.workflowScheduler.grpc.resource_allocator.gencode.ResourceRequest.resourceDemand getAllTasksRequest() {
    return allTasksRequest_ == null ? bit.workflowScheduler.grpc.resource_allocator.gencode.ResourceRequest.resourceDemand.getDefaultInstance() : allTasksRequest_;
  }
  /**
   * <pre>
   *当前该调度器所有待分配任务资源请求总量
   * </pre>
   *
   * <code>.bit.workflowScheduler.grpc.resource_allocator.gencode.ResourceRequest.resourceDemand allTasksRequest = 5;</code>
   */
  public bit.workflowScheduler.grpc.resource_allocator.gencode.ResourceRequest.resourceDemandOrBuilder getAllTasksRequestOrBuilder() {
    return getAllTasksRequest();
  }

  public static final int CUSTOMIZATION_FIELD_NUMBER = 6;
  private boolean customization_;
  /**
   * <pre>
   *time_grade暂时用不到。若customization=true且cost_grade=false，则请求的资源都满足；否则，按之前流程走
   * </pre>
   *
   * <code>bool customization = 6;</code>
   */
  public boolean getCustomization() {
    return customization_;
  }

  public static final int TIME_GRADE_FIELD_NUMBER = 7;
  private boolean timeGrade_;
  /**
   * <pre>
   * 是否存在时间等级
   * </pre>
   *
   * <code>bool time_grade = 7;</code>
   */
  public boolean getTimeGrade() {
    return timeGrade_;
  }

  public static final int COST_GRADE_FIELD_NUMBER = 8;
  private boolean costGrade_;
  /**
   * <pre>
   * 是否花费（资金）等级
   * </pre>
   *
   * <code>bool cost_grade = 8;</code>
   */
  public boolean getCostGrade() {
    return costGrade_;
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getSchedulerIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, schedulerId_);
    }
    if (timeStamp_ != 0L) {
      output.writeInt64(2, timeStamp_);
    }
    if (currentRequest_ != null) {
      output.writeMessage(3, getCurrentRequest());
    }
    if (nextRequest_ != null) {
      output.writeMessage(4, getNextRequest());
    }
    if (allTasksRequest_ != null) {
      output.writeMessage(5, getAllTasksRequest());
    }
    if (customization_ != false) {
      output.writeBool(6, customization_);
    }
    if (timeGrade_ != false) {
      output.writeBool(7, timeGrade_);
    }
    if (costGrade_ != false) {
      output.writeBool(8, costGrade_);
    }
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getSchedulerIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, schedulerId_);
    }
    if (timeStamp_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(2, timeStamp_);
    }
    if (currentRequest_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, getCurrentRequest());
    }
    if (nextRequest_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, getNextRequest());
    }
    if (allTasksRequest_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(5, getAllTasksRequest());
    }
    if (customization_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(6, customization_);
    }
    if (timeGrade_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(7, timeGrade_);
    }
    if (costGrade_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(8, costGrade_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof bit.workflowScheduler.grpc.resource_allocator.gencode.ResourceRequest)) {
      return super.equals(obj);
    }
    bit.workflowScheduler.grpc.resource_allocator.gencode.ResourceRequest other = (bit.workflowScheduler.grpc.resource_allocator.gencode.ResourceRequest) obj;

    boolean result = true;
    result = result && getSchedulerId()
        .equals(other.getSchedulerId());
    result = result && (getTimeStamp()
        == other.getTimeStamp());
    result = result && (hasCurrentRequest() == other.hasCurrentRequest());
    if (hasCurrentRequest()) {
      result = result && getCurrentRequest()
          .equals(other.getCurrentRequest());
    }
    result = result && (hasNextRequest() == other.hasNextRequest());
    if (hasNextRequest()) {
      result = result && getNextRequest()
          .equals(other.getNextRequest());
    }
    result = result && (hasAllTasksRequest() == other.hasAllTasksRequest());
    if (hasAllTasksRequest()) {
      result = result && getAllTasksRequest()
          .equals(other.getAllTasksRequest());
    }
    result = result && (getCustomization()
        == other.getCustomization());
    result = result && (getTimeGrade()
        == other.getTimeGrade());
    result = result && (getCostGrade()
        == other.getCostGrade());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + SCHEDULERID_FIELD_NUMBER;
    hash = (53 * hash) + getSchedulerId().hashCode();
    hash = (37 * hash) + TIMESTAMP_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getTimeStamp());
    if (hasCurrentRequest()) {
      hash = (37 * hash) + CURRENTREQUEST_FIELD_NUMBER;
      hash = (53 * hash) + getCurrentRequest().hashCode();
    }
    if (hasNextRequest()) {
      hash = (37 * hash) + NEXTREQUEST_FIELD_NUMBER;
      hash = (53 * hash) + getNextRequest().hashCode();
    }
    if (hasAllTasksRequest()) {
      hash = (37 * hash) + ALLTASKSREQUEST_FIELD_NUMBER;
      hash = (53 * hash) + getAllTasksRequest().hashCode();
    }
    hash = (37 * hash) + CUSTOMIZATION_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getCustomization());
    hash = (37 * hash) + TIME_GRADE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getTimeGrade());
    hash = (37 * hash) + COST_GRADE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getCostGrade());
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static bit.workflowScheduler.grpc.resource_allocator.gencode.ResourceRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static bit.workflowScheduler.grpc.resource_allocator.gencode.ResourceRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static bit.workflowScheduler.grpc.resource_allocator.gencode.ResourceRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static bit.workflowScheduler.grpc.resource_allocator.gencode.ResourceRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static bit.workflowScheduler.grpc.resource_allocator.gencode.ResourceRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static bit.workflowScheduler.grpc.resource_allocator.gencode.ResourceRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static bit.workflowScheduler.grpc.resource_allocator.gencode.ResourceRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static bit.workflowScheduler.grpc.resource_allocator.gencode.ResourceRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static bit.workflowScheduler.grpc.resource_allocator.gencode.ResourceRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static bit.workflowScheduler.grpc.resource_allocator.gencode.ResourceRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static bit.workflowScheduler.grpc.resource_allocator.gencode.ResourceRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static bit.workflowScheduler.grpc.resource_allocator.gencode.ResourceRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(bit.workflowScheduler.grpc.resource_allocator.gencode.ResourceRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   *资源请求参数
   * </pre>
   *
   * Protobuf type {@code bit.workflowScheduler.grpc.resource_allocator.gencode.ResourceRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:bit.workflowScheduler.grpc.resource_allocator.gencode.ResourceRequest)
      bit.workflowScheduler.grpc.resource_allocator.gencode.ResourceRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return bit.workflowScheduler.grpc.resource_allocator.gencode.ResourceAllocator.internal_static_bit_workflowScheduler_grpc_resource_allocator_gencode_ResourceRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return bit.workflowScheduler.grpc.resource_allocator.gencode.ResourceAllocator.internal_static_bit_workflowScheduler_grpc_resource_allocator_gencode_ResourceRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              bit.workflowScheduler.grpc.resource_allocator.gencode.ResourceRequest.class, bit.workflowScheduler.grpc.resource_allocator.gencode.ResourceRequest.Builder.class);
    }

    // Construct using bit.workflowScheduler.grpc.resource_allocator.gencode.ResourceRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      schedulerId_ = "";

      timeStamp_ = 0L;

      if (currentRequestBuilder_ == null) {
        currentRequest_ = null;
      } else {
        currentRequest_ = null;
        currentRequestBuilder_ = null;
      }
      if (nextRequestBuilder_ == null) {
        nextRequest_ = null;
      } else {
        nextRequest_ = null;
        nextRequestBuilder_ = null;
      }
      if (allTasksRequestBuilder_ == null) {
        allTasksRequest_ = null;
      } else {
        allTasksRequest_ = null;
        allTasksRequestBuilder_ = null;
      }
      customization_ = false;

      timeGrade_ = false;

      costGrade_ = false;

      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return bit.workflowScheduler.grpc.resource_allocator.gencode.ResourceAllocator.internal_static_bit_workflowScheduler_grpc_resource_allocator_gencode_ResourceRequest_descriptor;
    }

    public bit.workflowScheduler.grpc.resource_allocator.gencode.ResourceRequest getDefaultInstanceForType() {
      return bit.workflowScheduler.grpc.resource_allocator.gencode.ResourceRequest.getDefaultInstance();
    }

    public bit.workflowScheduler.grpc.resource_allocator.gencode.ResourceRequest build() {
      bit.workflowScheduler.grpc.resource_allocator.gencode.ResourceRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public bit.workflowScheduler.grpc.resource_allocator.gencode.ResourceRequest buildPartial() {
      bit.workflowScheduler.grpc.resource_allocator.gencode.ResourceRequest result = new bit.workflowScheduler.grpc.resource_allocator.gencode.ResourceRequest(this);
      result.schedulerId_ = schedulerId_;
      result.timeStamp_ = timeStamp_;
      if (currentRequestBuilder_ == null) {
        result.currentRequest_ = currentRequest_;
      } else {
        result.currentRequest_ = currentRequestBuilder_.build();
      }
      if (nextRequestBuilder_ == null) {
        result.nextRequest_ = nextRequest_;
      } else {
        result.nextRequest_ = nextRequestBuilder_.build();
      }
      if (allTasksRequestBuilder_ == null) {
        result.allTasksRequest_ = allTasksRequest_;
      } else {
        result.allTasksRequest_ = allTasksRequestBuilder_.build();
      }
      result.customization_ = customization_;
      result.timeGrade_ = timeGrade_;
      result.costGrade_ = costGrade_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof bit.workflowScheduler.grpc.resource_allocator.gencode.ResourceRequest) {
        return mergeFrom((bit.workflowScheduler.grpc.resource_allocator.gencode.ResourceRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(bit.workflowScheduler.grpc.resource_allocator.gencode.ResourceRequest other) {
      if (other == bit.workflowScheduler.grpc.resource_allocator.gencode.ResourceRequest.getDefaultInstance()) return this;
      if (!other.getSchedulerId().isEmpty()) {
        schedulerId_ = other.schedulerId_;
        onChanged();
      }
      if (other.getTimeStamp() != 0L) {
        setTimeStamp(other.getTimeStamp());
      }
      if (other.hasCurrentRequest()) {
        mergeCurrentRequest(other.getCurrentRequest());
      }
      if (other.hasNextRequest()) {
        mergeNextRequest(other.getNextRequest());
      }
      if (other.hasAllTasksRequest()) {
        mergeAllTasksRequest(other.getAllTasksRequest());
      }
      if (other.getCustomization() != false) {
        setCustomization(other.getCustomization());
      }
      if (other.getTimeGrade() != false) {
        setTimeGrade(other.getTimeGrade());
      }
      if (other.getCostGrade() != false) {
        setCostGrade(other.getCostGrade());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      bit.workflowScheduler.grpc.resource_allocator.gencode.ResourceRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (bit.workflowScheduler.grpc.resource_allocator.gencode.ResourceRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object schedulerId_ = "";
    /**
     * <pre>
     *调度器id
     * </pre>
     *
     * <code>string schedulerId = 1;</code>
     */
    public java.lang.String getSchedulerId() {
      java.lang.Object ref = schedulerId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        schedulerId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     *调度器id
     * </pre>
     *
     * <code>string schedulerId = 1;</code>
     */
    public com.google.protobuf.ByteString
        getSchedulerIdBytes() {
      java.lang.Object ref = schedulerId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        schedulerId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *调度器id
     * </pre>
     *
     * <code>string schedulerId = 1;</code>
     */
    public Builder setSchedulerId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      schedulerId_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *调度器id
     * </pre>
     *
     * <code>string schedulerId = 1;</code>
     */
    public Builder clearSchedulerId() {
      
      schedulerId_ = getDefaultInstance().getSchedulerId();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *调度器id
     * </pre>
     *
     * <code>string schedulerId = 1;</code>
     */
    public Builder setSchedulerIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      schedulerId_ = value;
      onChanged();
      return this;
    }

    private long timeStamp_ ;
    /**
     * <pre>
     *时间戳
     * </pre>
     *
     * <code>int64 timeStamp = 2;</code>
     */
    public long getTimeStamp() {
      return timeStamp_;
    }
    /**
     * <pre>
     *时间戳
     * </pre>
     *
     * <code>int64 timeStamp = 2;</code>
     */
    public Builder setTimeStamp(long value) {
      
      timeStamp_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *时间戳
     * </pre>
     *
     * <code>int64 timeStamp = 2;</code>
     */
    public Builder clearTimeStamp() {
      
      timeStamp_ = 0L;
      onChanged();
      return this;
    }

    private bit.workflowScheduler.grpc.resource_allocator.gencode.ResourceRequest.resourceDemand currentRequest_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        bit.workflowScheduler.grpc.resource_allocator.gencode.ResourceRequest.resourceDemand, bit.workflowScheduler.grpc.resource_allocator.gencode.ResourceRequest.resourceDemand.Builder, bit.workflowScheduler.grpc.resource_allocator.gencode.ResourceRequest.resourceDemandOrBuilder> currentRequestBuilder_;
    /**
     * <pre>
     *该调度器当前批次ready_tasks资源请求量
     * </pre>
     *
     * <code>.bit.workflowScheduler.grpc.resource_allocator.gencode.ResourceRequest.resourceDemand currentRequest = 3;</code>
     */
    public boolean hasCurrentRequest() {
      return currentRequestBuilder_ != null || currentRequest_ != null;
    }
    /**
     * <pre>
     *该调度器当前批次ready_tasks资源请求量
     * </pre>
     *
     * <code>.bit.workflowScheduler.grpc.resource_allocator.gencode.ResourceRequest.resourceDemand currentRequest = 3;</code>
     */
    public bit.workflowScheduler.grpc.resource_allocator.gencode.ResourceRequest.resourceDemand getCurrentRequest() {
      if (currentRequestBuilder_ == null) {
        return currentRequest_ == null ? bit.workflowScheduler.grpc.resource_allocator.gencode.ResourceRequest.resourceDemand.getDefaultInstance() : currentRequest_;
      } else {
        return currentRequestBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     *该调度器当前批次ready_tasks资源请求量
     * </pre>
     *
     * <code>.bit.workflowScheduler.grpc.resource_allocator.gencode.ResourceRequest.resourceDemand currentRequest = 3;</code>
     */
    public Builder setCurrentRequest(bit.workflowScheduler.grpc.resource_allocator.gencode.ResourceRequest.resourceDemand value) {
      if (currentRequestBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        currentRequest_ = value;
        onChanged();
      } else {
        currentRequestBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <pre>
     *该调度器当前批次ready_tasks资源请求量
     * </pre>
     *
     * <code>.bit.workflowScheduler.grpc.resource_allocator.gencode.ResourceRequest.resourceDemand currentRequest = 3;</code>
     */
    public Builder setCurrentRequest(
        bit.workflowScheduler.grpc.resource_allocator.gencode.ResourceRequest.resourceDemand.Builder builderForValue) {
      if (currentRequestBuilder_ == null) {
        currentRequest_ = builderForValue.build();
        onChanged();
      } else {
        currentRequestBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <pre>
     *该调度器当前批次ready_tasks资源请求量
     * </pre>
     *
     * <code>.bit.workflowScheduler.grpc.resource_allocator.gencode.ResourceRequest.resourceDemand currentRequest = 3;</code>
     */
    public Builder mergeCurrentRequest(bit.workflowScheduler.grpc.resource_allocator.gencode.ResourceRequest.resourceDemand value) {
      if (currentRequestBuilder_ == null) {
        if (currentRequest_ != null) {
          currentRequest_ =
            bit.workflowScheduler.grpc.resource_allocator.gencode.ResourceRequest.resourceDemand.newBuilder(currentRequest_).mergeFrom(value).buildPartial();
        } else {
          currentRequest_ = value;
        }
        onChanged();
      } else {
        currentRequestBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <pre>
     *该调度器当前批次ready_tasks资源请求量
     * </pre>
     *
     * <code>.bit.workflowScheduler.grpc.resource_allocator.gencode.ResourceRequest.resourceDemand currentRequest = 3;</code>
     */
    public Builder clearCurrentRequest() {
      if (currentRequestBuilder_ == null) {
        currentRequest_ = null;
        onChanged();
      } else {
        currentRequest_ = null;
        currentRequestBuilder_ = null;
      }

      return this;
    }
    /**
     * <pre>
     *该调度器当前批次ready_tasks资源请求量
     * </pre>
     *
     * <code>.bit.workflowScheduler.grpc.resource_allocator.gencode.ResourceRequest.resourceDemand currentRequest = 3;</code>
     */
    public bit.workflowScheduler.grpc.resource_allocator.gencode.ResourceRequest.resourceDemand.Builder getCurrentRequestBuilder() {
      
      onChanged();
      return getCurrentRequestFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     *该调度器当前批次ready_tasks资源请求量
     * </pre>
     *
     * <code>.bit.workflowScheduler.grpc.resource_allocator.gencode.ResourceRequest.resourceDemand currentRequest = 3;</code>
     */
    public bit.workflowScheduler.grpc.resource_allocator.gencode.ResourceRequest.resourceDemandOrBuilder getCurrentRequestOrBuilder() {
      if (currentRequestBuilder_ != null) {
        return currentRequestBuilder_.getMessageOrBuilder();
      } else {
        return currentRequest_ == null ?
            bit.workflowScheduler.grpc.resource_allocator.gencode.ResourceRequest.resourceDemand.getDefaultInstance() : currentRequest_;
      }
    }
    /**
     * <pre>
     *该调度器当前批次ready_tasks资源请求量
     * </pre>
     *
     * <code>.bit.workflowScheduler.grpc.resource_allocator.gencode.ResourceRequest.resourceDemand currentRequest = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        bit.workflowScheduler.grpc.resource_allocator.gencode.ResourceRequest.resourceDemand, bit.workflowScheduler.grpc.resource_allocator.gencode.ResourceRequest.resourceDemand.Builder, bit.workflowScheduler.grpc.resource_allocator.gencode.ResourceRequest.resourceDemandOrBuilder> 
        getCurrentRequestFieldBuilder() {
      if (currentRequestBuilder_ == null) {
        currentRequestBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            bit.workflowScheduler.grpc.resource_allocator.gencode.ResourceRequest.resourceDemand, bit.workflowScheduler.grpc.resource_allocator.gencode.ResourceRequest.resourceDemand.Builder, bit.workflowScheduler.grpc.resource_allocator.gencode.ResourceRequest.resourceDemandOrBuilder>(
                getCurrentRequest(),
                getParentForChildren(),
                isClean());
        currentRequest_ = null;
      }
      return currentRequestBuilder_;
    }

    private bit.workflowScheduler.grpc.resource_allocator.gencode.ResourceRequest.resourceDemand nextRequest_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        bit.workflowScheduler.grpc.resource_allocator.gencode.ResourceRequest.resourceDemand, bit.workflowScheduler.grpc.resource_allocator.gencode.ResourceRequest.resourceDemand.Builder, bit.workflowScheduler.grpc.resource_allocator.gencode.ResourceRequest.resourceDemandOrBuilder> nextRequestBuilder_;
    /**
     * <pre>
     *该调度器下一批次ready_tasks资源请求量
     * </pre>
     *
     * <code>.bit.workflowScheduler.grpc.resource_allocator.gencode.ResourceRequest.resourceDemand nextRequest = 4;</code>
     */
    public boolean hasNextRequest() {
      return nextRequestBuilder_ != null || nextRequest_ != null;
    }
    /**
     * <pre>
     *该调度器下一批次ready_tasks资源请求量
     * </pre>
     *
     * <code>.bit.workflowScheduler.grpc.resource_allocator.gencode.ResourceRequest.resourceDemand nextRequest = 4;</code>
     */
    public bit.workflowScheduler.grpc.resource_allocator.gencode.ResourceRequest.resourceDemand getNextRequest() {
      if (nextRequestBuilder_ == null) {
        return nextRequest_ == null ? bit.workflowScheduler.grpc.resource_allocator.gencode.ResourceRequest.resourceDemand.getDefaultInstance() : nextRequest_;
      } else {
        return nextRequestBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     *该调度器下一批次ready_tasks资源请求量
     * </pre>
     *
     * <code>.bit.workflowScheduler.grpc.resource_allocator.gencode.ResourceRequest.resourceDemand nextRequest = 4;</code>
     */
    public Builder setNextRequest(bit.workflowScheduler.grpc.resource_allocator.gencode.ResourceRequest.resourceDemand value) {
      if (nextRequestBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        nextRequest_ = value;
        onChanged();
      } else {
        nextRequestBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <pre>
     *该调度器下一批次ready_tasks资源请求量
     * </pre>
     *
     * <code>.bit.workflowScheduler.grpc.resource_allocator.gencode.ResourceRequest.resourceDemand nextRequest = 4;</code>
     */
    public Builder setNextRequest(
        bit.workflowScheduler.grpc.resource_allocator.gencode.ResourceRequest.resourceDemand.Builder builderForValue) {
      if (nextRequestBuilder_ == null) {
        nextRequest_ = builderForValue.build();
        onChanged();
      } else {
        nextRequestBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <pre>
     *该调度器下一批次ready_tasks资源请求量
     * </pre>
     *
     * <code>.bit.workflowScheduler.grpc.resource_allocator.gencode.ResourceRequest.resourceDemand nextRequest = 4;</code>
     */
    public Builder mergeNextRequest(bit.workflowScheduler.grpc.resource_allocator.gencode.ResourceRequest.resourceDemand value) {
      if (nextRequestBuilder_ == null) {
        if (nextRequest_ != null) {
          nextRequest_ =
            bit.workflowScheduler.grpc.resource_allocator.gencode.ResourceRequest.resourceDemand.newBuilder(nextRequest_).mergeFrom(value).buildPartial();
        } else {
          nextRequest_ = value;
        }
        onChanged();
      } else {
        nextRequestBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <pre>
     *该调度器下一批次ready_tasks资源请求量
     * </pre>
     *
     * <code>.bit.workflowScheduler.grpc.resource_allocator.gencode.ResourceRequest.resourceDemand nextRequest = 4;</code>
     */
    public Builder clearNextRequest() {
      if (nextRequestBuilder_ == null) {
        nextRequest_ = null;
        onChanged();
      } else {
        nextRequest_ = null;
        nextRequestBuilder_ = null;
      }

      return this;
    }
    /**
     * <pre>
     *该调度器下一批次ready_tasks资源请求量
     * </pre>
     *
     * <code>.bit.workflowScheduler.grpc.resource_allocator.gencode.ResourceRequest.resourceDemand nextRequest = 4;</code>
     */
    public bit.workflowScheduler.grpc.resource_allocator.gencode.ResourceRequest.resourceDemand.Builder getNextRequestBuilder() {
      
      onChanged();
      return getNextRequestFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     *该调度器下一批次ready_tasks资源请求量
     * </pre>
     *
     * <code>.bit.workflowScheduler.grpc.resource_allocator.gencode.ResourceRequest.resourceDemand nextRequest = 4;</code>
     */
    public bit.workflowScheduler.grpc.resource_allocator.gencode.ResourceRequest.resourceDemandOrBuilder getNextRequestOrBuilder() {
      if (nextRequestBuilder_ != null) {
        return nextRequestBuilder_.getMessageOrBuilder();
      } else {
        return nextRequest_ == null ?
            bit.workflowScheduler.grpc.resource_allocator.gencode.ResourceRequest.resourceDemand.getDefaultInstance() : nextRequest_;
      }
    }
    /**
     * <pre>
     *该调度器下一批次ready_tasks资源请求量
     * </pre>
     *
     * <code>.bit.workflowScheduler.grpc.resource_allocator.gencode.ResourceRequest.resourceDemand nextRequest = 4;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        bit.workflowScheduler.grpc.resource_allocator.gencode.ResourceRequest.resourceDemand, bit.workflowScheduler.grpc.resource_allocator.gencode.ResourceRequest.resourceDemand.Builder, bit.workflowScheduler.grpc.resource_allocator.gencode.ResourceRequest.resourceDemandOrBuilder> 
        getNextRequestFieldBuilder() {
      if (nextRequestBuilder_ == null) {
        nextRequestBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            bit.workflowScheduler.grpc.resource_allocator.gencode.ResourceRequest.resourceDemand, bit.workflowScheduler.grpc.resource_allocator.gencode.ResourceRequest.resourceDemand.Builder, bit.workflowScheduler.grpc.resource_allocator.gencode.ResourceRequest.resourceDemandOrBuilder>(
                getNextRequest(),
                getParentForChildren(),
                isClean());
        nextRequest_ = null;
      }
      return nextRequestBuilder_;
    }

    private bit.workflowScheduler.grpc.resource_allocator.gencode.ResourceRequest.resourceDemand allTasksRequest_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        bit.workflowScheduler.grpc.resource_allocator.gencode.ResourceRequest.resourceDemand, bit.workflowScheduler.grpc.resource_allocator.gencode.ResourceRequest.resourceDemand.Builder, bit.workflowScheduler.grpc.resource_allocator.gencode.ResourceRequest.resourceDemandOrBuilder> allTasksRequestBuilder_;
    /**
     * <pre>
     *当前该调度器所有待分配任务资源请求总量
     * </pre>
     *
     * <code>.bit.workflowScheduler.grpc.resource_allocator.gencode.ResourceRequest.resourceDemand allTasksRequest = 5;</code>
     */
    public boolean hasAllTasksRequest() {
      return allTasksRequestBuilder_ != null || allTasksRequest_ != null;
    }
    /**
     * <pre>
     *当前该调度器所有待分配任务资源请求总量
     * </pre>
     *
     * <code>.bit.workflowScheduler.grpc.resource_allocator.gencode.ResourceRequest.resourceDemand allTasksRequest = 5;</code>
     */
    public bit.workflowScheduler.grpc.resource_allocator.gencode.ResourceRequest.resourceDemand getAllTasksRequest() {
      if (allTasksRequestBuilder_ == null) {
        return allTasksRequest_ == null ? bit.workflowScheduler.grpc.resource_allocator.gencode.ResourceRequest.resourceDemand.getDefaultInstance() : allTasksRequest_;
      } else {
        return allTasksRequestBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     *当前该调度器所有待分配任务资源请求总量
     * </pre>
     *
     * <code>.bit.workflowScheduler.grpc.resource_allocator.gencode.ResourceRequest.resourceDemand allTasksRequest = 5;</code>
     */
    public Builder setAllTasksRequest(bit.workflowScheduler.grpc.resource_allocator.gencode.ResourceRequest.resourceDemand value) {
      if (allTasksRequestBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        allTasksRequest_ = value;
        onChanged();
      } else {
        allTasksRequestBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <pre>
     *当前该调度器所有待分配任务资源请求总量
     * </pre>
     *
     * <code>.bit.workflowScheduler.grpc.resource_allocator.gencode.ResourceRequest.resourceDemand allTasksRequest = 5;</code>
     */
    public Builder setAllTasksRequest(
        bit.workflowScheduler.grpc.resource_allocator.gencode.ResourceRequest.resourceDemand.Builder builderForValue) {
      if (allTasksRequestBuilder_ == null) {
        allTasksRequest_ = builderForValue.build();
        onChanged();
      } else {
        allTasksRequestBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <pre>
     *当前该调度器所有待分配任务资源请求总量
     * </pre>
     *
     * <code>.bit.workflowScheduler.grpc.resource_allocator.gencode.ResourceRequest.resourceDemand allTasksRequest = 5;</code>
     */
    public Builder mergeAllTasksRequest(bit.workflowScheduler.grpc.resource_allocator.gencode.ResourceRequest.resourceDemand value) {
      if (allTasksRequestBuilder_ == null) {
        if (allTasksRequest_ != null) {
          allTasksRequest_ =
            bit.workflowScheduler.grpc.resource_allocator.gencode.ResourceRequest.resourceDemand.newBuilder(allTasksRequest_).mergeFrom(value).buildPartial();
        } else {
          allTasksRequest_ = value;
        }
        onChanged();
      } else {
        allTasksRequestBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <pre>
     *当前该调度器所有待分配任务资源请求总量
     * </pre>
     *
     * <code>.bit.workflowScheduler.grpc.resource_allocator.gencode.ResourceRequest.resourceDemand allTasksRequest = 5;</code>
     */
    public Builder clearAllTasksRequest() {
      if (allTasksRequestBuilder_ == null) {
        allTasksRequest_ = null;
        onChanged();
      } else {
        allTasksRequest_ = null;
        allTasksRequestBuilder_ = null;
      }

      return this;
    }
    /**
     * <pre>
     *当前该调度器所有待分配任务资源请求总量
     * </pre>
     *
     * <code>.bit.workflowScheduler.grpc.resource_allocator.gencode.ResourceRequest.resourceDemand allTasksRequest = 5;</code>
     */
    public bit.workflowScheduler.grpc.resource_allocator.gencode.ResourceRequest.resourceDemand.Builder getAllTasksRequestBuilder() {
      
      onChanged();
      return getAllTasksRequestFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     *当前该调度器所有待分配任务资源请求总量
     * </pre>
     *
     * <code>.bit.workflowScheduler.grpc.resource_allocator.gencode.ResourceRequest.resourceDemand allTasksRequest = 5;</code>
     */
    public bit.workflowScheduler.grpc.resource_allocator.gencode.ResourceRequest.resourceDemandOrBuilder getAllTasksRequestOrBuilder() {
      if (allTasksRequestBuilder_ != null) {
        return allTasksRequestBuilder_.getMessageOrBuilder();
      } else {
        return allTasksRequest_ == null ?
            bit.workflowScheduler.grpc.resource_allocator.gencode.ResourceRequest.resourceDemand.getDefaultInstance() : allTasksRequest_;
      }
    }
    /**
     * <pre>
     *当前该调度器所有待分配任务资源请求总量
     * </pre>
     *
     * <code>.bit.workflowScheduler.grpc.resource_allocator.gencode.ResourceRequest.resourceDemand allTasksRequest = 5;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        bit.workflowScheduler.grpc.resource_allocator.gencode.ResourceRequest.resourceDemand, bit.workflowScheduler.grpc.resource_allocator.gencode.ResourceRequest.resourceDemand.Builder, bit.workflowScheduler.grpc.resource_allocator.gencode.ResourceRequest.resourceDemandOrBuilder> 
        getAllTasksRequestFieldBuilder() {
      if (allTasksRequestBuilder_ == null) {
        allTasksRequestBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            bit.workflowScheduler.grpc.resource_allocator.gencode.ResourceRequest.resourceDemand, bit.workflowScheduler.grpc.resource_allocator.gencode.ResourceRequest.resourceDemand.Builder, bit.workflowScheduler.grpc.resource_allocator.gencode.ResourceRequest.resourceDemandOrBuilder>(
                getAllTasksRequest(),
                getParentForChildren(),
                isClean());
        allTasksRequest_ = null;
      }
      return allTasksRequestBuilder_;
    }

    private boolean customization_ ;
    /**
     * <pre>
     *time_grade暂时用不到。若customization=true且cost_grade=false，则请求的资源都满足；否则，按之前流程走
     * </pre>
     *
     * <code>bool customization = 6;</code>
     */
    public boolean getCustomization() {
      return customization_;
    }
    /**
     * <pre>
     *time_grade暂时用不到。若customization=true且cost_grade=false，则请求的资源都满足；否则，按之前流程走
     * </pre>
     *
     * <code>bool customization = 6;</code>
     */
    public Builder setCustomization(boolean value) {
      
      customization_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *time_grade暂时用不到。若customization=true且cost_grade=false，则请求的资源都满足；否则，按之前流程走
     * </pre>
     *
     * <code>bool customization = 6;</code>
     */
    public Builder clearCustomization() {
      
      customization_ = false;
      onChanged();
      return this;
    }

    private boolean timeGrade_ ;
    /**
     * <pre>
     * 是否存在时间等级
     * </pre>
     *
     * <code>bool time_grade = 7;</code>
     */
    public boolean getTimeGrade() {
      return timeGrade_;
    }
    /**
     * <pre>
     * 是否存在时间等级
     * </pre>
     *
     * <code>bool time_grade = 7;</code>
     */
    public Builder setTimeGrade(boolean value) {
      
      timeGrade_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 是否存在时间等级
     * </pre>
     *
     * <code>bool time_grade = 7;</code>
     */
    public Builder clearTimeGrade() {
      
      timeGrade_ = false;
      onChanged();
      return this;
    }

    private boolean costGrade_ ;
    /**
     * <pre>
     * 是否花费（资金）等级
     * </pre>
     *
     * <code>bool cost_grade = 8;</code>
     */
    public boolean getCostGrade() {
      return costGrade_;
    }
    /**
     * <pre>
     * 是否花费（资金）等级
     * </pre>
     *
     * <code>bool cost_grade = 8;</code>
     */
    public Builder setCostGrade(boolean value) {
      
      costGrade_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 是否花费（资金）等级
     * </pre>
     *
     * <code>bool cost_grade = 8;</code>
     */
    public Builder clearCostGrade() {
      
      costGrade_ = false;
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:bit.workflowScheduler.grpc.resource_allocator.gencode.ResourceRequest)
  }

  // @@protoc_insertion_point(class_scope:bit.workflowScheduler.grpc.resource_allocator.gencode.ResourceRequest)
  private static final bit.workflowScheduler.grpc.resource_allocator.gencode.ResourceRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new bit.workflowScheduler.grpc.resource_allocator.gencode.ResourceRequest();
  }

  public static bit.workflowScheduler.grpc.resource_allocator.gencode.ResourceRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ResourceRequest>
      PARSER = new com.google.protobuf.AbstractParser<ResourceRequest>() {
    public ResourceRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new ResourceRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ResourceRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ResourceRequest> getParserForType() {
    return PARSER;
  }

  public bit.workflowScheduler.grpc.resource_allocator.gencode.ResourceRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

